import 'package:freezed_annotation/freezed_annotation.dart';

part 'protocol_info.freezed.dart'; // Will be generated by build_runner
part 'protocol_info.g.dart'; // Will be generated by build_runner

@freezed
class ProtocolInfo with _$ProtocolInfo {
  const factory ProtocolInfo({
    required String name,
    required String path,
    required String description,
    required String version,
    required String author,
    @JsonKey(name: 'created_at') required DateTime createdAt,
    required List<String> tags,
    @JsonKey(name: 'is_verified') required bool isVerified,
    @JsonKey(name: 'is_favorite')
    bool? isFavorite, // Nullable for optional fields
    @JsonKey(name: 'last_run_at') DateTime? lastRunAt, // Nullable
    @JsonKey(name: 'run_count') int? runCount, // Nullable
  }) = _ProtocolInfo;

  // Factory constructor for creating a new ProtocolInfo instance from a map (JSON).
  factory ProtocolInfo.fromJson(Map<String, dynamic> json) =>
      _$ProtocolInfoFromJson(json);
}
