# ruff.toml

select = [
    "E",
    "F",
    "G",
    "D",
    "I",
]

# ignore = ["E501"] # Example: ignore line too long for general code

line-length = 88
indent-width = 2
fix = true
target-version = "py310"

[format]
indent-style = "space"




[lint.pydocstyle]
# ignore = ["D415"]
