# ruff.toml

line-length = 100
indent-width = 2
fix = true
target-version = "py310"
exclude = ["praxis/backend/commons"]

[lint]
select = ["ALL"]
# ignore = ["E501"] # Example: ignore line too long for general code

[format]
indent-style = "space"

[lint.pydocstyle]
# ignore = ["D415"]