"""inject_shell.py --with-coxswain behavior: the Coxswain panel <script
type=module> tag rides INSIDE the same PRAXIS-SHELL-INJECT block, only under
the flag (FR-12); a default build's injected block stays byte-identical to its
historical shape, and --check fails loud on a flag/build mismatch.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

_SCRIPTS_DIR = Path(__file__).resolve().parents[1] / "scripts"
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

import inject_shell  # noqa: E402 -- path setup must precede this import


ANCHOR_HTML = (
    "<!doctype html><html><head></head><body>"
    '<div id="jupyter-lite-main"></div></body></html>'
)


def _make_entry(tmp_path: Path, *, with_module_file: bool = True) -> Path:
    entry = tmp_path / "repl" / "index.html"
    entry.parent.mkdir(parents=True)
    shell = tmp_path / "shell" / "praxis-shell.js"
    shell.parent.mkdir(parents=True)
    shell.write_text("// shell\n")
    if with_module_file:
        module = tmp_path / "shell" / "coxswain-shell.js"
        module.write_text("// coxswain panel\n")
    entry.write_text(ANCHOR_HTML)
    return entry


def test_default_block_is_byte_identical_to_historical_shape() -> None:
    block = inject_shell._render_block("dev", "../shell/praxis-shell.js")
    assert block == (
        "<!-- PRAXIS-SHELL-INJECT:BEGIN (D1, ADR Sec 2.3 -- generated by "
        "inject_shell.py, do not hand-edit) -->\n"
        '<script>window.PRAXIS_GIT_SHA = "dev";</script>\n'
        '<script src="../shell/praxis-shell.js"></script>\n'
        "<!-- PRAXIS-SHELL-INJECT:END -->"
    )
    assert "coxswain" not in block


def test_flagged_block_adds_exactly_one_module_tag_inside_the_markers() -> None:
    block = inject_shell._render_block("dev", "../shell/praxis-shell.js", with_coxswain=True)
    assert block.count("coxswain-shell.js") == 1
    assert '<script type="module" src="../shell/coxswain-shell.js"></script>' in block
    # still inside the same marker pair
    assert block.index(inject_shell._BEGIN_MARKER) < block.index("coxswain-shell.js")
    assert block.index("coxswain-shell.js") < block.index(inject_shell._END_MARKER)


def test_check_passes_on_a_correctly_flagged_build(tmp_path: Path) -> None:
    entry = _make_entry(tmp_path)
    html = entry.read_text()
    entry.write_text(inject_shell.inject(html, "dev", "../shell/praxis-shell.js", with_coxswain=True))
    inject_shell.check(entry, "../shell/praxis-shell.js", require_coxswain=True)  # must not raise


def test_check_fails_loud_when_flag_is_set_but_tag_is_missing(tmp_path: Path) -> None:
    entry = _make_entry(tmp_path, with_module_file=False)
    html = entry.read_text()
    entry.write_text(inject_shell.inject(html, "dev", "../shell/praxis-shell.js"))
    with pytest.raises(inject_shell.InjectError, match="no coxswain-shell"):
        inject_shell.check(entry, "../shell/praxis-shell.js", require_coxswain=True)


def test_check_fails_when_tag_present_but_module_file_missing_on_disk(tmp_path: Path) -> None:
    entry = _make_entry(tmp_path, with_module_file=False)
    html = entry.read_text()
    entry.write_text(inject_shell.inject(html, "dev", "../shell/praxis-shell.js", with_coxswain=True))
    with pytest.raises(inject_shell.InjectError, match="does not exist on disk"):
        inject_shell.check(entry, "../shell/praxis-shell.js", require_coxswain=True)


def test_default_check_ignores_absence_of_the_tag(tmp_path: Path) -> None:
    entry = _make_entry(tmp_path, with_module_file=False)
    html = entry.read_text()
    entry.write_text(inject_shell.inject(html, "dev", "../shell/praxis-shell.js"))
    # A default build must pass a default check unchanged (back-compat).
    inject_shell.check(entry, "../shell/praxis-shell.js")
