"""D2 tests (ADR Sec 2.3) for ``web-repl/scripts/build_manifest.py``: the
manifest is the only filename seam, sources are enumerated from disk (never
hardcoded), the write is atomic via ``os.replace``, and per-entry sha256
detects both wheel and source drift.

Pure CPython. Uses a scratch ``--web-repl-root`` fixture tree under
``tmp_path`` rather than the real (currently sparse -- see the task's own
report) ``web-repl/overlay/assets/{shims,python}``, so this test is not
gated on other Phase 3 tasks having relocated those files yet.
"""

from __future__ import annotations

import io
import json
import sys
import zipfile
from pathlib import Path

import pytest

_SCRIPTS_DIR = Path(__file__).resolve().parents[1] / "scripts"
if str(_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS_DIR))

import build_manifest  # noqa: E402 -- path setup must precede this import


def _make_fake_wheel(path: Path, *, package: str, version: str = "1.2.3") -> None:
    path.write_bytes(f"not a real wheel, just needs to exist -- {package}".encode())


def _make_pylabrobot_wheel(path: Path, *, source_sha: str, version: str = "0.1.6+gdeadbeef") -> None:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr(
            "pylabrobot/_praxis_build_info.py",
            "# Generated by build_wheels.py. Do not edit by hand.\n"
            f"PLR_SOURCE_SHA = {source_sha!r}\n"
            "BUILD_ID = '20260101T000000Z-deadbeef'\n",
        )
        zf.writestr("pylabrobot/__init__.py", "")
    path.write_bytes(buf.getvalue())


def _make_tree(tmp_path: Path) -> Path:
    """A scratch web-repl/ root: overlay/assets/{wheels,shims,python/praxis}."""
    root = tmp_path / "web-repl"
    wheels_dir = root / "overlay" / "assets" / "wheels"
    shims_dir = root / "overlay" / "assets" / "shims"
    python_dir = root / "overlay" / "assets" / "python"
    praxis_pkg_dir = python_dir / "praxis"
    for d in (wheels_dir, shims_dir, praxis_pkg_dir):
        d.mkdir(parents=True, exist_ok=True)

    _make_pylabrobot_wheel(
        wheels_dir / "pylabrobot-0.1.6+gdeadbeef-py3-none-any.whl",
        source_sha="d9651e2098cd269fc47e6aff80c9242a82d1b587",
    )
    _make_fake_wheel(wheels_dir / "pylibftdi-0.0.0-py3-none-any.whl", package="pylibftdi")

    (shims_dir / "web_serial_shim.py").write_text("# web serial shim\n")
    (shims_dir / "web_usb_shim.py").write_text("# web usb shim\n")
    (shims_dir / "__init__.py").write_text("")
    (python_dir / "web_bridge.py").write_text("# web bridge\n")
    (praxis_pkg_dir / "__init__.py").write_text("")  # 0-byte, ADR Sec 2.4
    (praxis_pkg_dir / "interactive.py").write_text("# pause()/confirm()/input()\n")

    # A __pycache__ dir that must NEVER show up in the sources array.
    pycache = shims_dir / "__pycache__"
    pycache.mkdir()
    (pycache / "web_serial_shim.cpython-314.pyc").write_bytes(b"\x00\x01")

    return root


def test_collect_wheels_parses_both_packages(tmp_path: Path) -> None:
    root = _make_tree(tmp_path)
    wheels = build_manifest.collect_wheels(root / "overlay" / "assets" / "wheels")
    by_package = {w["package"]: w for w in wheels}
    assert set(by_package) == {"pylabrobot", "pylibftdi"}
    assert by_package["pylabrobot"]["source_sha"] == "d9651e2098cd269fc47e6aff80c9242a82d1b587"
    assert by_package["pylibftdi"]["source_sha"] is None  # OQ-6: never invented
    for entry in wheels:
        assert entry["sha256"]
        assert entry["bytes"] > 0


def test_collect_sources_enumerates_from_disk_not_a_hardcoded_list(tmp_path: Path) -> None:
    root = _make_tree(tmp_path)
    sources = build_manifest.collect_sources(root / "overlay")
    paths = {s["path"] for s in sources}
    # shims/__init__.py is deliberately excluded (F-VFS): shims are imported
    # as bare top-level modules (stages.import_shim_class), never as a
    # `shims` package, so transport.py's dest_for_source() would otherwise
    # flatten it to a bare `__init__.py` at the VFS root -- see
    # test_collect_sources_excludes_shims_init_py below.
    assert paths == {
        "assets/shims/web_serial_shim.py",
        "assets/shims/web_usb_shim.py",
        "assets/python/web_bridge.py",
        "assets/python/praxis/__init__.py",
        "assets/python/praxis/interactive.py",
    }


def test_collect_sources_excludes_shims_init_py(tmp_path: Path) -> None:
    """F-VFS: shims/__init__.py must never be manifested. It exists on disk
    (see _make_tree) but is imported nowhere -- stages.import_shim_class()
    imports each shim by bare top-level module name, never through a
    `shims` package -- and transport.dest_for_source() strips SHIMS_PREFIX
    unconditionally, so if this entry ever reached the manifest it would
    resolve to `__init__.py` at the VFS root, turning the bootstrap's own
    working directory into a package.
    """
    root = _make_tree(tmp_path)
    assert (root / "overlay" / "assets" / "shims" / "__init__.py").is_file()
    sources = build_manifest.collect_sources(root / "overlay")
    paths = {s["path"] for s in sources}
    assert "assets/shims/__init__.py" not in paths
    # __pycache__ / .pyc must never leak into the seam.
    assert not any("__pycache__" in p or p.endswith(".pyc") for p in paths)
    # The 0-byte praxis/__init__.py is INCLUDED -- D2 covers its presence.
    zero_byte = next(s for s in sources if s["path"] == "assets/python/praxis/__init__.py")
    assert zero_byte["sha256"] == build_manifest._sha256_file(
        root / "overlay" / "assets" / "python" / "praxis" / "__init__.py"
    )


def test_manifest_written_atomically_via_os_replace(tmp_path: Path) -> None:
    root = _make_tree(tmp_path)
    manifest = build_manifest.build_manifest(web_repl_root=root, repo_root=root, dev=True)
    dest = root / "overlay" / "assets" / "wheels" / "manifest.json"
    build_manifest.write_manifest_atomic(manifest, dest)
    assert dest.is_file()
    on_disk = json.loads(dest.read_text())
    assert on_disk["praxis_git_sha"] == "dev"
    assert len(on_disk["wheels"]) == 2
    # 5, not the fixture's 6 files: shims/__init__.py is deliberately
    # excluded (F-VFS) -- see test_collect_sources_excludes_shims_init_py.
    assert len(on_disk["sources"]) == 5
    # No leftover temp file from the atomic-write dance.
    leftovers = list(dest.parent.glob(".manifest-*"))
    assert leftovers == []


def test_dev_flag_writes_dev_sentinel_not_a_real_sha(tmp_path: Path) -> None:
    root = _make_tree(tmp_path)
    manifest = build_manifest.build_manifest(web_repl_root=root, repo_root=root, dev=True)
    assert manifest["praxis_git_sha"] == "dev"


def test_verify_manifest_clean_tree_reports_no_problems(tmp_path: Path) -> None:
    root = _make_tree(tmp_path)
    manifest = build_manifest.build_manifest(web_repl_root=root, repo_root=root, dev=True)
    problems = build_manifest.verify_manifest(manifest, web_repl_root=root)
    assert problems == []


def test_verify_manifest_detects_corrupted_source_file(tmp_path: Path) -> None:
    """THE OBSERVED-FAILING NEGATIVE TEST the task's Verify section asks for:
    generate a manifest, corrupt one source file's bytes WITHOUT
    regenerating, and show the sha256 comparison catching it.
    """
    root = _make_tree(tmp_path)
    manifest = build_manifest.build_manifest(web_repl_root=root, repo_root=root, dev=True)
    assert build_manifest.verify_manifest(manifest, web_repl_root=root) == []  # sanity: clean first

    target = root / "overlay" / "assets" / "python" / "web_bridge.py"
    target.write_text("# TAMPERED -- byte-level drift, no regeneration\n")

    problems = build_manifest.verify_manifest(manifest, web_repl_root=root)
    assert len(problems) == 1
    assert "assets/python/web_bridge.py" in problems[0]
    assert "mismatch" in problems[0]


def test_verify_manifest_detects_corrupted_wheel(tmp_path: Path) -> None:
    root = _make_tree(tmp_path)
    manifest = build_manifest.build_manifest(web_repl_root=root, repo_root=root, dev=True)

    wheel_path = root / "overlay" / "assets" / "wheels" / "pylibftdi-0.0.0-py3-none-any.whl"
    wheel_path.write_bytes(b"corrupted wheel bytes")

    problems = build_manifest.verify_manifest(manifest, web_repl_root=root)
    assert any("pylibftdi" in p and ("mismatch" in p) for p in problems)


def test_no_source_dirs_yet_is_a_warning_not_an_error(tmp_path: Path) -> None:
    """Today's real web-repl/overlay/assets/ has only wheels/ populated --
    shims/ and python/ are relocated by earlier, separate Phase 3 tasks. The
    generator must not treat their absence as fatal.
    """
    root = tmp_path / "web-repl"
    wheels_dir = root / "overlay" / "assets" / "wheels"
    wheels_dir.mkdir(parents=True)
    _make_fake_wheel(wheels_dir / "pylibftdi-0.0.0-py3-none-any.whl", package="pylibftdi")
    manifest = build_manifest.build_manifest(web_repl_root=root, repo_root=root, dev=True)
    assert manifest["sources"] == []
    assert len(manifest["wheels"]) == 1


def test_missing_wheels_dir_is_fatal(tmp_path: Path) -> None:
    root = tmp_path / "web-repl"
    (root / "overlay" / "assets").mkdir(parents=True)
    with pytest.raises(build_manifest.ManifestError):
        build_manifest.build_manifest(web_repl_root=root, repo_root=root, dev=True)


def test_source_code_actually_uses_os_replace() -> None:
    """Direct check for the ADR's 'preserved verbatim: atomic manifest.json
    via os.replace' requirement, independent of behavioral coverage above.
    """
    text = (_SCRIPTS_DIR / "build_manifest.py").read_text()
    assert "os.replace(" in text
