"""Factories for creating test data."""
import factory
import time
import random
import uuid
from factory.alchemy import SQLAlchemyModelFactory

from praxis.backend.models.orm.deck import DeckDefinitionOrm, DeckOrm
from praxis.backend.models.orm.machine import MachineOrm
from praxis.backend.models.orm.outputs import FunctionDataOutputOrm, WellDataOutputOrm
from praxis.backend.models.orm.protocol import (
    FunctionCallLogOrm,
    FunctionProtocolDefinitionOrm,
    ProtocolRunOrm,
)
from praxis.backend.models.orm.resource import ResourceDefinitionOrm, ResourceOrm
from praxis.backend.models.orm.workcell import WorkcellOrm


_last_v7_timestamp = None


def uuid7():
    """The UUIDv7 format is designed to encode a Unix timestamp with
    arbitrary sub-second precision. The key property provided by UUIDv7
    is that timestamp values generated by one system and parsed by
    another are guaranteed to have sub-second precision of either the
    generator or the parser, whichever is less. Additionally, the system
    parsing the UUIDv7 value does not need to know which precision was
    used during encoding in order to function correctly."""
    global _last_v7_timestamp
    nanoseconds = time.time_ns()
    if _last_v7_timestamp is not None and nanoseconds <= _last_v7_timestamp:
        nanoseconds = _last_v7_timestamp + 1
    _last_v7_timestamp = nanoseconds
    timestamp_ms, timestamp_ns_frac = divmod(nanoseconds, 10**6)
    rand_a = random.getrandbits(12)
    rand_b = random.getrandbits(62)
    uuid_int = (timestamp_ms & 0xFFFFFFFFFFFF) << 80
    uuid_int |= (7 & 0xF) << 76
    uuid_int |= (rand_a & 0xFFF) << 64
    uuid_int |= (2 & 0x3) << 62
    uuid_int |= (rand_b & 0x3FFFFFFFFFFFFFFF)
    return uuid.UUID(int=uuid_int)


class WorkcellFactory(SQLAlchemyModelFactory):
    """Factory for WorkcellOrm."""

    class Meta:
        """Meta class for WorkcellFactory."""

        model = WorkcellOrm

    accession_id = factory.LazyFunction(uuid7)
    name = factory.Faker("word")


class MachineFactory(SQLAlchemyModelFactory):
    """Factory for MachineOrm."""

    class Meta:
        """Meta class for MachineFactory."""

        model = MachineOrm

    accession_id = factory.LazyFunction(uuid7)
    name = factory.Faker("word")
    fqn = factory.Faker("word")
    workcell_accession_id = factory.SelfAttribute("workcell.accession_id")

    workcell = factory.SubFactory(
        "tests.factories.WorkcellFactory",
    )


class ResourceDefinitionFactory(SQLAlchemyModelFactory):
    """Factory for ResourceDefinitionOrm."""

    class Meta:
        """Meta class for ResourceDefinitionOrm."""

        model = ResourceDefinitionOrm

    name = factory.Faker("word")
    fqn = factory.Faker("word")


class DeckDefinitionFactory(SQLAlchemyModelFactory):
    """Factory for DeckDefinitionOrm."""

    class Meta:
        """Meta class for DeckDefinitionOrm."""

        model = DeckDefinitionOrm

    name = factory.Faker("word")
    fqn = factory.Faker("word")
    resource_definition = factory.SubFactory(
        "tests.factories.ResourceDefinitionFactory",
    )

    @classmethod
    def _create(cls, model_class, *args, **kwargs):
        """Create a deck definition and a resource definition."""
        resource_definition = ResourceDefinitionFactory()
        kwargs["resource_definition"] = resource_definition
        return super()._create(model_class, *args, **kwargs)


class DeckFactory(SQLAlchemyModelFactory):
    """Factory for DeckOrm."""

    class Meta:
        """Meta class for DeckOrm."""
        model = DeckOrm

    class Params:
        # Transient parameters to build dependencies without passing them to the model's __init__
        deck_type_def = factory.SubFactory(DeckDefinitionFactory)
        machine_def = factory.SubFactory(MachineFactory)

    accession_id = factory.LazyFunction(uuid7)
    name = factory.Faker("word")

    # Use the transient parameters to correctly populate the model's foreign key fields.
    deck_type_id = factory.LazyAttribute(lambda o: o.deck_type_def.accession_id)
    parent_machine_accession_id = factory.LazyAttribute(lambda o: o.machine_def.accession_id)
    resource_definition_accession_id = factory.LazyAttribute(
        lambda o: o.deck_type_def.resource_definition.accession_id
    )


class ResourceFactory(SQLAlchemyModelFactory):
    """Factory for ResourceOrm."""

    class Meta:
        """Meta class for ResourceFactory."""

        model = ResourceOrm

    name = factory.Faker("word")
    resource_definition = factory.SubFactory(ResourceDefinitionFactory)


class FunctionProtocolDefinitionFactory(SQLAlchemyModelFactory):
    """Factory for FunctionProtocolDefinitionOrm."""

    class Meta:
        """Meta class for FunctionProtocolDefinitionFactory."""

        model = FunctionProtocolDefinitionOrm

    name = "test_protocol"
    fqn = "test_protocol"


class ProtocolRunFactory(SQLAlchemyModelFactory):
    """Factory for ProtocolRunOrm."""

    class Meta:
        """Meta class for ProtocolRunFactory."""

        model = ProtocolRunOrm

    top_level_protocol_definition = factory.SubFactory(FunctionProtocolDefinitionFactory)


class FunctionCallLogFactory(SQLAlchemyModelFactory):
    """Factory for FunctionCallLogOrm."""

    class Meta:
        """Meta class for FunctionCallLogFactory."""

        model = FunctionCallLogOrm

    protocol_run = factory.SubFactory(ProtocolRunFactory)
    sequence_in_run = 0
    executed_function_definition = factory.SubFactory(FunctionProtocolDefinitionFactory)


class FunctionDataOutputFactory(SQLAlchemyModelFactory):
    """Factory for FunctionDataOutputOrm."""

    class Meta:
        """Meta class for FunctionDataOutputFactory."""

        model = FunctionDataOutputOrm

    class Params:
        # Create a transient protocol_run that can be shared.
        pr = factory.SubFactory(ProtocolRunFactory)

    # Create the function_call_log using the transient protocol_run.
    function_call_log = factory.SubFactory(
        FunctionCallLogFactory, protocol_run=factory.SelfAttribute("..pr")
    )


class WellDataOutputFactory(SQLAlchemyModelFactory):
    """Factory for WellDataOutputOrm."""

    class Meta:
        """Meta class for WellDataOutputFactory."""

        model = WellDataOutputOrm

    function_data_output = factory.SubFactory(FunctionDataOutputFactory)
    plate_resource = factory.SubFactory(ResourceFactory)
    well_name = "A1"
    well_row = 0
    well_column = 0
    well_index = 0
    data_value = factory.Faker("pyfloat")
