"""Factories for creating test data."""
import random
import time
import uuid

import factory
from factory.alchemy import SQLAlchemyModelFactory

from praxis.backend.models.orm.deck import DeckDefinitionOrm, DeckOrm
from praxis.backend.models.orm.machine import MachineOrm
from praxis.backend.models.orm.outputs import FunctionDataOutputOrm, WellDataOutputOrm
from praxis.backend.models.orm.protocol import (
    FunctionCallLogOrm,
    FunctionProtocolDefinitionOrm,
    ProtocolRunOrm,
)
from praxis.backend.models.orm.resource import ResourceDefinitionOrm, ResourceOrm
from praxis.backend.models.orm.workcell import WorkcellOrm
from praxis.backend.models.enums import AssetType

_last_v7_timestamp = None


def uuid7():
    """The UUIDv7 format is designed to encode a Unix timestamp with
    arbitrary sub-second precision. The key property provided by UUIDv7
    is that timestamp values generated by one system and parsed by
    another are guaranteed to have sub-second precision of either the
    generator or the parser, whichever is less. Additionally, the system
    parsing the UUIDv7 value does not need to know which precision was
    used during encoding in order to function correctly.
    """
    global _last_v7_timestamp
    nanoseconds = time.time_ns()
    if _last_v7_timestamp is not None and nanoseconds <= _last_v7_timestamp:
        nanoseconds = _last_v7_timestamp + 1
    _last_v7_timestamp = nanoseconds
    timestamp_ms, _timestamp_ns_frac = divmod(nanoseconds, 10**6)
    rand_a = random.getrandbits(12)
    rand_b = random.getrandbits(62)
    uuid_int = (timestamp_ms & 0xFFFFFFFFFFFF) << 80
    uuid_int |= (7 & 0xF) << 76
    uuid_int |= (rand_a & 0xFFF) << 64
    uuid_int |= (2 & 0x3) << 62
    uuid_int |= (rand_b & 0x3FFFFFFFFFFFFFFF)
    return uuid.UUID(int=uuid_int)


class WorkcellFactory(SQLAlchemyModelFactory):

    """Factory for WorkcellOrm."""

    class Meta:

        """Meta class for WorkcellFactory."""

        model = WorkcellOrm

    name = factory.Faker("word")


class MachineFactory(SQLAlchemyModelFactory):

    """Factory for MachineOrm."""

    class Meta:

        """Meta class for MachineFactory."""

        model = MachineOrm

    name = factory.Faker("word")
    fqn = factory.Faker("word")
    asset_type = AssetType.MACHINE
    workcell_accession_id = factory.SelfAttribute("workcell.accession_id")

    workcell = factory.SubFactory(
        "tests.factories.WorkcellFactory",
    )


class ResourceDefinitionFactory(SQLAlchemyModelFactory):

    """Factory for ResourceDefinitionOrm."""

    class Meta:

        """Meta class for ResourceDefinitionOrm."""

        model = ResourceDefinitionOrm

    name = factory.Faker("word")
    fqn = factory.Faker("word")
    plr_definition_details_json = {"num_items_x": 12, "num_items_y": 8}


class DeckDefinitionFactory(SQLAlchemyModelFactory):

    """Factory for DeckDefinitionOrm."""

    class Meta:

        """Meta class for DeckDefinitionOrm."""

        model = DeckDefinitionOrm

    name = factory.Faker("word")
    fqn = factory.Faker("word")
    resource_definition = factory.SubFactory(
        "tests.factories.ResourceDefinitionFactory",
    )

    resource_definition = factory.SubFactory(
        "tests.factories.ResourceDefinitionFactory",
    )


class DeckFactory(SQLAlchemyModelFactory):

    """Factory for DeckOrm."""

    class Meta:

        """Meta class for DeckOrm."""

        model = DeckOrm

    class Params:
        # Transient parameters to build dependencies without passing them to the model's __init__
        deck_type_def = factory.SubFactory(DeckDefinitionFactory)
        machine_def = factory.SubFactory(MachineFactory)

    name = factory.Faker("word")
    asset_type = AssetType.DECK

    # Use the transient parameters to correctly populate the model's foreign key fields.
    deck_type_id = factory.LazyAttribute(lambda o: o.deck_type_def.accession_id)
    parent_machine_accession_id = factory.LazyAttribute(lambda o: o.machine_def.accession_id)
    resource_definition_accession_id = factory.LazyAttribute(
        lambda o: o.deck_type_def.resource_definition.accession_id,
    )


class ResourceFactory(SQLAlchemyModelFactory):
    """Factory for ResourceOrm."""

    class Meta:
        """Meta class for ResourceFactory."""

        model = ResourceOrm

    class Params:
        res_def = factory.SubFactory(ResourceDefinitionFactory)

    name = factory.Faker("word")
    asset_type = AssetType.RESOURCE
    resource_definition_accession_id = factory.LazyAttribute(
        lambda o: o.res_def.accession_id
    )


class FunctionProtocolDefinitionFactory(SQLAlchemyModelFactory):
    """Factory for FunctionProtocolDefinitionOrm."""

    class Meta:
        """Meta class for FunctionProtocolDefinitionFactory."""

        model = FunctionProtocolDefinitionOrm

    name = "test_protocol"
    fqn = "test_protocol"


class ProtocolRunFactory(SQLAlchemyModelFactory):
    """Factory for ProtocolRunOrm."""

    class Meta:
        """Meta class for ProtocolRunFactory."""

        model = ProtocolRunOrm

    class Params:
        top_level_def = factory.SubFactory(FunctionProtocolDefinitionFactory)

    name = factory.Faker("word")
    accession_id = factory.LazyFunction(uuid7)
    top_level_protocol_definition_accession_id = factory.LazyAttribute(
        lambda o: o.top_level_def.accession_id
    )


class FunctionCallLogFactory(SQLAlchemyModelFactory):
    """Factory for FunctionCallLogOrm."""

    class Meta:
        """Meta class for FunctionCallLogOrm."""

        model = FunctionCallLogOrm

    class Params:
        protocol_run_obj = factory.SubFactory(ProtocolRunFactory)
        executed_function_def = factory.SubFactory(FunctionProtocolDefinitionFactory)

    name = factory.Faker("word")
    accession_id = factory.LazyFunction(uuid7)
    protocol_run_accession_id = factory.LazyAttribute(
        lambda o: o.protocol_run_obj.accession_id
    )
    sequence_in_run = 0
    function_protocol_definition_accession_id = factory.LazyAttribute(
        lambda o: o.executed_function_def.accession_id
    )


class FunctionDataOutputFactory(SQLAlchemyModelFactory):
    """Factory for FunctionDataOutputOrm."""

    class Meta:
        """Meta class for FunctionDataOutputFactory."""

        model = FunctionDataOutputOrm
        exclude = ("_function_call_log",)

    class Params:
        pass

    name = factory.Faker("word")
    accession_id = factory.LazyFunction(uuid7)
    
    _function_call_log = factory.SubFactory(FunctionCallLogFactory)
    
    function_call_log_accession_id = factory.SelfAttribute("_function_call_log.accession_id")
    protocol_run_accession_id = factory.SelfAttribute("_function_call_log.protocol_run_accession_id")


class WellDataOutputFactory(SQLAlchemyModelFactory):
    """Factory for WellDataOutputOrm."""

    class Meta:
        """Meta class for WellDataOutputOrm."""

        model = WellDataOutputOrm
        exclude = ("_function_data_output", "_plate_resource")

    class Params:
        pass

    name = factory.Faker("word")
    
    _function_data_output = factory.SubFactory(FunctionDataOutputFactory)
    _plate_resource = factory.SubFactory(ResourceFactory)
    
    function_data_output_accession_id = factory.SelfAttribute("_function_data_output.accession_id")
    plate_resource_accession_id = factory.SelfAttribute("_plate_resource.accession_id")
    
    well_name = "A1"
    well_row = 0
    well_column = 0
    well_index = 0
    data_value = factory.Faker("pyfloat")
