"""v0.1_alpha_baseline

Revision ID: 8bb1b518a5ae
Revises: 
Create Date: 2026-01-21 09:33:34.433870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '8bb1b518a5ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_definition_catalog',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('fqn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('positioning_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plr_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_size_x_mm', sa.Float(), nullable=True),
    sa.Column('default_size_y_mm', sa.Float(), nullable=True),
    sa.Column('default_size_z_mm', sa.Float(), nullable=True),
    sa.Column('serialized_constructor_args_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('serialized_assignment_methods_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('serialized_constructor_hints_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('additional_properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('positioning_config_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('asset_requirement_accession_id', sa.Uuid(), nullable=True),
    sa.Column('resource_definition_accession_id', sa.Uuid(), nullable=True),
    sa.Column('parent_accession_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['asset_requirement_accession_id'], ['protocol_asset_requirements.accession_id'], ),
    sa.ForeignKeyConstraint(['parent_accession_id'], ['deck_definition_catalog.accession_id'], ),
    sa.ForeignKeyConstraint(['resource_definition_accession_id'], ['resource_definitions.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id')
    )
    with op.batch_alter_table('deck_definition_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deck_definition_catalog_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deck_definition_catalog_fqn'), ['fqn'], unique=True)

    op.create_table('decks',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('asset_type', sa.Enum('MACHINE', 'RESOURCE', 'MACHINE_RESOURCE', 'DECK', 'ASSET', name='assettype'), nullable=False),
    sa.Column('fqn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plr_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('plr_definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE_IN_STORAGE', 'AVAILABLE_ON_DECK', 'IN_USE', 'EMPTY', 'PARTIALLY_FILLED', 'FULL', 'NEEDS_REFILL', 'TO_BE_DISPOSED', 'DISPOSED', 'TO_BE_CLEANED', 'CLEANED', 'ERROR', 'UNKNOWN', name='resourcestatusenum'), nullable=False),
    sa.Column('status_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_deck_position_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_accession_id', sa.Uuid(), nullable=True),
    sa.Column('parent_machine_accession_id', sa.Uuid(), nullable=True),
    sa.Column('deck_type_id', sa.Uuid(), nullable=True),
    sa.Column('workcell_accession_id', sa.Uuid(), nullable=True),
    sa.Column('resource_definition_accession_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['deck_type_id'], ['deck_definition_catalog.accession_id'], ),
    sa.ForeignKeyConstraint(['parent_machine_accession_id'], ['machines.accession_id'], ),
    sa.ForeignKeyConstraint(['resource_definition_accession_id'], ['resource_definitions.accession_id'], ),
    sa.ForeignKeyConstraint(['workcell_accession_id'], ['workcells.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id')
    )
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decks_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decks_fqn'), ['fqn'], unique=False)
        batch_op.create_index(batch_op.f('ix_decks_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_decks_name'), ['name'], unique=True)

    op.create_table('file_system_protocol_sources',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('base_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_recursive', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'SYNCING', 'INACTIVE', 'SYNC_ERROR', 'PENDING_DELETION', name='protocolsourcestatusenum'), nullable=True),
    sa.PrimaryKeyConstraint('accession_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('file_system_protocol_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_system_protocol_sources_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_system_protocol_sources_name'), ['name'], unique=False)

    op.create_table('machines',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('asset_type', sa.Enum('MACHINE', 'RESOURCE', 'MACHINE_RESOURCE', 'DECK', 'ASSET', name='assettype'), nullable=False),
    sa.Column('fqn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plr_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('plr_definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('status_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_simulation_override', sa.Boolean(), nullable=True),
    sa.Column('last_seen_online', sa.DateTime(), nullable=True),
    sa.Column('maintenance_enabled', sa.Boolean(), nullable=False),
    sa.Column('connection_info', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('user_configured_capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('maintenance_schedule_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('last_maintenance_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('simulation_backend_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('machine_category', sa.Enum('LIQUID_HANDLER', 'PLATE_READER', 'INCUBATOR', 'SHAKER', 'HEATER_SHAKER', 'PUMP', 'FAN', 'TEMPERATURE_CONTROLLER', 'TILTING', 'THERMOCYCLER', 'SEALER', 'FLOW_CYTOMETER', 'SCALE', 'CENTRIFUGE', 'ARM', 'GENERAL_AUTOMATION_DEVICE', 'OTHER_INSTRUMENT', 'UNKNOWN', name='machinecategoryenum'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'ERROR', 'OFFLINE', 'INITIALIZING', 'MAINTENANCE', name='machinestatusenum'), nullable=False),
    sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workcell_accession_id', sa.Uuid(), nullable=True),
    sa.Column('resource_counterpart_accession_id', sa.Uuid(), nullable=True),
    sa.Column('deck_child_accession_id', sa.Uuid(), nullable=True),
    sa.Column('deck_child_definition_accession_id', sa.Uuid(), nullable=True),
    sa.Column('current_protocol_run_accession_id', sa.Uuid(), nullable=True),
    sa.Column('machine_definition_accession_id', sa.Uuid(), nullable=True),
    sa.Column('frontend_definition_accession_id', sa.Uuid(), nullable=True),
    sa.Column('backend_definition_accession_id', sa.Uuid(), nullable=True),
    sa.Column('backend_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['backend_definition_accession_id'], ['machine_backend_definitions.accession_id'], ),
    sa.ForeignKeyConstraint(['current_protocol_run_accession_id'], ['protocol_runs.accession_id'], ),
    sa.ForeignKeyConstraint(['deck_child_accession_id'], ['decks.accession_id'], ),
    sa.ForeignKeyConstraint(['deck_child_definition_accession_id'], ['deck_definition_catalog.accession_id'], ),
    sa.ForeignKeyConstraint(['frontend_definition_accession_id'], ['machine_frontend_definitions.accession_id'], ),
    sa.ForeignKeyConstraint(['machine_definition_accession_id'], ['machine_definitions.accession_id'], ),
    sa.ForeignKeyConstraint(['resource_counterpart_accession_id'], ['resources.accession_id'], ),
    sa.ForeignKeyConstraint(['workcell_accession_id'], ['workcells.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machines_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_fqn'), ['fqn'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_last_seen_online'), ['last_seen_online'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_machines_serial_number'), ['serial_number'], unique=True)

    op.create_table('protocol_source_repositories',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('git_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('local_checkout_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_synced_commit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'SYNCING', 'INACTIVE', 'SYNC_ERROR', 'PENDING_DELETION', name='protocolsourcestatusenum'), nullable=True),
    sa.Column('auto_sync_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('accession_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('protocol_source_repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protocol_source_repositories_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_source_repositories_git_url'), ['git_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_source_repositories_name'), ['name'], unique=False)

    op.create_table('resource_definitions',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('fqn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plr_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_consumable', sa.Boolean(), nullable=False),
    sa.Column('is_reusable', sa.Boolean(), nullable=False),
    sa.Column('nominal_volume_ul', sa.Float(), nullable=True),
    sa.Column('material', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ordering', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_x_mm', sa.Float(), nullable=True),
    sa.Column('size_y_mm', sa.Float(), nullable=True),
    sa.Column('size_z_mm', sa.Float(), nullable=True),
    sa.Column('num_items', sa.Integer(), nullable=True),
    sa.Column('plate_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('well_volume_ul', sa.Float(), nullable=True),
    sa.Column('tip_volume_ul', sa.Float(), nullable=True),
    sa.Column('vendor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plr_definition_details_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('rotation_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('deck_definition_accession_id', sa.Uuid(), nullable=True),
    sa.Column('asset_requirement_accession_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['asset_requirement_accession_id'], ['protocol_asset_requirements.accession_id'], ),
    sa.ForeignKeyConstraint(['deck_definition_accession_id'], ['deck_definition_catalog.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id')
    )
    with op.batch_alter_table('resource_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_definitions_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_definitions_asset_requirement_accession_id'), ['asset_requirement_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_definitions_deck_definition_accession_id'), ['deck_definition_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_definitions_fqn'), ['fqn'], unique=True)
        batch_op.create_index(batch_op.f('ix_resource_definitions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_definitions_num_items'), ['num_items'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_definitions_plate_type'), ['plate_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_definitions_tip_volume_ul'), ['tip_volume_ul'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_definitions_vendor'), ['vendor'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_definitions_well_volume_ul'), ['well_volume_ul'], unique=False)

    op.create_table('resources',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('asset_type', sa.Enum('MACHINE', 'RESOURCE', 'MACHINE_RESOURCE', 'DECK', 'ASSET', name='assettype'), nullable=False),
    sa.Column('fqn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plr_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('plr_definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_deck_position_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE_IN_STORAGE', 'AVAILABLE_ON_DECK', 'IN_USE', 'EMPTY', 'PARTIALLY_FILLED', 'FULL', 'NEEDS_REFILL', 'TO_BE_DISPOSED', 'DISPOSED', 'TO_BE_CLEANED', 'CLEANED', 'ERROR', 'UNKNOWN', name='resourcestatusenum'), nullable=True),
    sa.Column('resource_definition_accession_id', sa.Uuid(), nullable=True),
    sa.Column('parent_accession_id', sa.Uuid(), nullable=True),
    sa.Column('current_protocol_run_accession_id', sa.Uuid(), nullable=True),
    sa.Column('machine_location_accession_id', sa.Uuid(), nullable=True),
    sa.Column('deck_location_accession_id', sa.Uuid(), nullable=True),
    sa.Column('workcell_accession_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['current_protocol_run_accession_id'], ['protocol_runs.accession_id'], ),
    sa.ForeignKeyConstraint(['deck_location_accession_id'], ['decks.accession_id'], ),
    sa.ForeignKeyConstraint(['machine_location_accession_id'], ['machines.accession_id'], ),
    sa.ForeignKeyConstraint(['parent_accession_id'], ['resources.accession_id'], ),
    sa.ForeignKeyConstraint(['resource_definition_accession_id'], ['resource_definitions.accession_id'], ),
    sa.ForeignKeyConstraint(['workcell_accession_id'], ['workcells.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_fqn'), ['fqn'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_carrier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('accession_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('workcells',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('fqn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('physical_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_state_update_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'IN_USE', 'RESERVED', 'AVAILABLE', 'ERROR', 'INACTIVE', 'MAINTENANCE', name='workcellstatusenum'), nullable=False),
    sa.Column('latest_state_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('accession_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('workcells', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workcells_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workcells_fqn'), ['fqn'], unique=False)
        batch_op.create_index(batch_op.f('ix_workcells_name'), ['name'], unique=False)

    op.create_table('deck_position_definitions',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('position_accession_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nominal_x_mm', sa.Float(), nullable=False),
    sa.Column('nominal_y_mm', sa.Float(), nullable=False),
    sa.Column('nominal_z_mm', sa.Float(), nullable=False),
    sa.Column('pylabrobot_position_type_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accepts_tips', sa.Boolean(), nullable=True),
    sa.Column('accepts_plates', sa.Boolean(), nullable=True),
    sa.Column('accepts_tubes', sa.Boolean(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('allowed_resource_definition_names', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('compatible_resource_fqns', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('deck_type_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['deck_type_id'], ['deck_definition_catalog.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id'),
    sa.UniqueConstraint('deck_type_id', 'position_accession_id')
    )
    with op.batch_alter_table('deck_position_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deck_position_definitions_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deck_position_definitions_deck_type_id'), ['deck_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deck_position_definitions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_deck_position_definitions_position_accession_id'), ['position_accession_id'], unique=False)

    op.create_table('function_protocol_definitions',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('fqn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('module_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('function_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_top_level', sa.Boolean(), nullable=False),
    sa.Column('solo_execution', sa.Boolean(), nullable=False),
    sa.Column('preconfigure_deck', sa.Boolean(), nullable=False),
    sa.Column('requires_deck', sa.Boolean(), nullable=False),
    sa.Column('deck_param_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deck_construction_function_fqn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deck_layout_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state_param_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deprecated', sa.Boolean(), nullable=False),
    sa.Column('source_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('graph_cached_at', sa.DateTime(), nullable=True),
    sa.Column('simulation_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('simulation_cached_at', sa.DateTime(), nullable=True),
    sa.Column('bytecode_python_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bytecode_cache_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bytecode_cached_at', sa.DateTime(), nullable=True),
    sa.Column('commit_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('hardware_requirements_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('data_views_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('computation_graph_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('setup_instructions_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('simulation_result_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('inferred_requirements_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('failure_modes_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('cached_bytecode', sa.LargeBinary(), nullable=True),
    sa.Column('source_repository_accession_id', sa.Uuid(), nullable=True),
    sa.Column('file_system_source_accession_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['file_system_source_accession_id'], ['file_system_protocol_sources.accession_id'], ),
    sa.ForeignKeyConstraint(['source_repository_accession_id'], ['protocol_source_repositories.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id'),
    sa.UniqueConstraint('name', 'version', 'file_system_source_accession_id', 'source_file_path'),
    sa.UniqueConstraint('name', 'version', 'source_repository_accession_id', 'commit_hash')
    )
    with op.batch_alter_table('function_protocol_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_function_protocol_definitions_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_protocol_definitions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_protocol_definitions_commit_hash'), ['commit_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_protocol_definitions_deprecated'), ['deprecated'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_protocol_definitions_file_system_source_accession_id'), ['file_system_source_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_protocol_definitions_fqn'), ['fqn'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_protocol_definitions_function_name'), ['function_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_protocol_definitions_is_top_level'), ['is_top_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_protocol_definitions_module_name'), ['module_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_protocol_definitions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_protocol_definitions_source_file_path'), ['source_file_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_protocol_definitions_source_repository_accession_id'), ['source_repository_accession_id'], unique=False)

    op.create_table('machine_frontend_definitions',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('fqn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plr_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('capabilities_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('has_deck', sa.Boolean(), nullable=False),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('machine_category', sa.Enum('LIQUID_HANDLER', 'PLATE_READER', 'INCUBATOR', 'SHAKER', 'HEATER_SHAKER', 'PUMP', 'FAN', 'TEMPERATURE_CONTROLLER', 'TILTING', 'THERMOCYCLER', 'SEALER', 'FLOW_CYTOMETER', 'SCALE', 'CENTRIFUGE', 'ARM', 'GENERAL_AUTOMATION_DEVICE', 'OTHER_INSTRUMENT', 'UNKNOWN', name='machinecategoryenum'), nullable=False),
    sa.Column('deck_definition_accession_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['deck_definition_accession_id'], ['deck_definition_catalog.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('machine_frontend_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_frontend_definitions_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machine_frontend_definitions_fqn'), ['fqn'], unique=True)
        batch_op.create_index(batch_op.f('ix_machine_frontend_definitions_name'), ['name'], unique=False)

    op.create_table('machine_backend_definitions',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('fqn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('connection_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('backend_type', sa.Enum('REAL_HARDWARE', 'SIMULATOR', 'CHATTERBOX', 'MOCK', name='backendtypeenum'), nullable=False),
    sa.Column('frontend_definition_accession_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['frontend_definition_accession_id'], ['machine_frontend_definitions.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('machine_backend_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_backend_definitions_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machine_backend_definitions_fqn'), ['fqn'], unique=True)
        batch_op.create_index(batch_op.f('ix_machine_backend_definitions_name'), ['name'], unique=False)

    op.create_table('parameter_definitions',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('type_hint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fqn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deck_param', sa.Boolean(), nullable=False),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.Column('default_value_repr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('field_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_itemized', sa.Boolean(), nullable=False),
    sa.Column('linked_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('constraints_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('itemized_spec_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('ui_hint_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('protocol_definition_accession_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_definition_accession_id'], ['function_protocol_definitions.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id'),
    sa.UniqueConstraint('protocol_definition_accession_id', 'name')
    )
    with op.batch_alter_table('parameter_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parameter_definitions_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parameter_definitions_fqn'), ['fqn'], unique=False)
        batch_op.create_index(batch_op.f('ix_parameter_definitions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_parameter_definitions_protocol_definition_accession_id'), ['protocol_definition_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parameter_definitions_type_hint'), ['type_hint'], unique=False)

    op.create_table('protocol_asset_requirements',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('type_hint_str', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fqn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('actual_type_str', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('optional', sa.Boolean(), nullable=False),
    sa.Column('default_value_repr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('required_plr_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('constraints_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('location_constraints_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('protocol_definition_accession_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_definition_accession_id'], ['function_protocol_definitions.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id'),
    sa.UniqueConstraint('protocol_definition_accession_id', 'name')
    )
    with op.batch_alter_table('protocol_asset_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protocol_asset_requirements_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_asset_requirements_actual_type_str'), ['actual_type_str'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_asset_requirements_fqn'), ['fqn'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_asset_requirements_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_asset_requirements_protocol_definition_accession_id'), ['protocol_definition_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_asset_requirements_required_plr_category'), ['required_plr_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_asset_requirements_type_hint_str'), ['type_hint_str'], unique=False)

    op.create_table('protocol_runs',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('data_directory_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PENDING', 'PREPARING', 'RUNNING', 'PAUSING', 'PAUSED', 'RESUMING', 'COMPLETED', 'FAILED', 'CANCELING', 'CANCELLED', 'INTERVENING', 'REQUIRES_INTERVENTION', name='protocolrunstatusenum'), nullable=True),
    sa.Column('input_parameters_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('resolved_assets_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('output_data_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('initial_state_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('final_state_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_by_user', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('top_level_protocol_definition_accession_id', sa.Uuid(), nullable=False),
    sa.Column('previous_accession_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['previous_accession_id'], ['protocol_runs.accession_id'], ),
    sa.ForeignKeyConstraint(['top_level_protocol_definition_accession_id'], ['function_protocol_definitions.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id')
    )
    with op.batch_alter_table('protocol_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protocol_runs_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_runs_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_runs_previous_accession_id'), ['previous_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_protocol_runs_top_level_protocol_definition_accession_id'), ['top_level_protocol_definition_accession_id'], unique=False)

    op.create_table('function_call_logs',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('sequence_in_run', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_traceback_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'ERROR', 'PENDING', 'IN_PROGRESS', 'SKIPPED', 'CANCELED', 'UNKNOWN', name='functioncallstatusenum'), nullable=True),
    sa.Column('input_args_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('return_value_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('state_before_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('state_after_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('protocol_run_accession_id', sa.Uuid(), nullable=False),
    sa.Column('function_protocol_definition_accession_id', sa.Uuid(), nullable=False),
    sa.Column('parent_function_call_log_accession_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['function_protocol_definition_accession_id'], ['function_protocol_definitions.accession_id'], ),
    sa.ForeignKeyConstraint(['parent_function_call_log_accession_id'], ['function_call_logs.accession_id'], ),
    sa.ForeignKeyConstraint(['protocol_run_accession_id'], ['protocol_runs.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id')
    )
    with op.batch_alter_table('function_call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_function_call_logs_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_call_logs_function_protocol_definition_accession_id'), ['function_protocol_definition_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_call_logs_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_call_logs_parent_function_call_log_accession_id'), ['parent_function_call_log_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_call_logs_protocol_run_accession_id'), ['protocol_run_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_call_logs_sequence_in_run'), ['sequence_in_run'], unique=False)

    op.create_table('machine_definitions',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('fqn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plr_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('material', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_x_mm', sa.Float(), nullable=True),
    sa.Column('size_y_mm', sa.Float(), nullable=True),
    sa.Column('size_z_mm', sa.Float(), nullable=True),
    sa.Column('frontend_fqn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nominal_volume_ul', sa.Float(), nullable=True),
    sa.Column('plr_definition_details_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('rotation_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('setup_method_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('compatible_backends', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('capabilities_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('connection_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('is_simulated_frontend', sa.Boolean(), nullable=True),
    sa.Column('available_simulation_backends', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('machine_category', sa.Enum('LIQUID_HANDLER', 'PLATE_READER', 'INCUBATOR', 'SHAKER', 'HEATER_SHAKER', 'PUMP', 'FAN', 'TEMPERATURE_CONTROLLER', 'TILTING', 'THERMOCYCLER', 'SEALER', 'FLOW_CYTOMETER', 'SCALE', 'CENTRIFUGE', 'ARM', 'GENERAL_AUTOMATION_DEVICE', 'OTHER_INSTRUMENT', 'UNKNOWN', name='machinecategoryenum'), nullable=False),
    sa.Column('has_deck', sa.Boolean(), nullable=False),
    sa.Column('resource_definition_accession_id', sa.Uuid(), nullable=True),
    sa.Column('deck_definition_accession_id', sa.Uuid(), nullable=True),
    sa.Column('asset_requirement_accession_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['asset_requirement_accession_id'], ['protocol_asset_requirements.accession_id'], ),
    sa.ForeignKeyConstraint(['deck_definition_accession_id'], ['deck_definition_catalog.accession_id'], ),
    sa.ForeignKeyConstraint(['resource_definition_accession_id'], ['resource_definitions.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('machine_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_definitions_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machine_definitions_fqn'), ['fqn'], unique=True)
        batch_op.create_index(batch_op.f('ix_machine_definitions_name'), ['name'], unique=False)

    op.create_table('schedule_entries',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RESERVED', 'READY_TO_EXECUTE', 'CELERY_QUEUED', 'EXECUTING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CONFLICT', 'TIMEOUT', name='schedulestatusenum'), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('execution_started_at', sa.DateTime(), nullable=True),
    sa.Column('execution_completed_at', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_ms', sa.Integer(), nullable=True),
    sa.Column('required_asset_count', sa.Integer(), nullable=False),
    sa.Column('user_params_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('asset_requirements_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('asset_analysis_completed_at', sa.DateTime(), nullable=True),
    sa.Column('assets_reserved_at', sa.DateTime(), nullable=True),
    sa.Column('celery_task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('celery_queue_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('initial_state_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('protocol_run_accession_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['protocol_run_accession_id'], ['protocol_runs.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id')
    )
    with op.batch_alter_table('schedule_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_entries_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_entries_celery_queue_name'), ['celery_queue_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_entries_celery_task_id'), ['celery_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_entries_execution_completed_at'), ['execution_completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_entries_execution_started_at'), ['execution_started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_entries_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_entries_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_entries_protocol_run_accession_id'), ['protocol_run_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_entries_scheduled_at'), ['scheduled_at'], unique=False)

    op.create_table('asset_reservations',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('reserved_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('asset_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('redis_lock_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('redis_lock_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lock_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('required_capabilities_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('estimated_usage_duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RESERVED', 'PENDING', 'ACTIVE', 'RELEASED', 'EXPIRED', 'FAILED', name='assetreservationstatusenum'), nullable=False),
    sa.Column('asset_type', sa.Enum('MACHINE', 'RESOURCE', 'MACHINE_RESOURCE', 'DECK', 'ASSET', name='assettype'), nullable=False),
    sa.Column('asset_accession_id', sa.UUID(), nullable=True),
    sa.Column('schedule_entry_accession_id', sa.Uuid(), nullable=False),
    sa.Column('protocol_run_accession_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_run_accession_id'], ['protocol_runs.accession_id'], ),
    sa.ForeignKeyConstraint(['schedule_entry_accession_id'], ['schedule_entries.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id')
    )
    with op.batch_alter_table('asset_reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_reservations_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_reservations_asset_name'), ['asset_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_reservations_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_reservations_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_reservations_protocol_run_accession_id'), ['protocol_run_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_reservations_redis_lock_key'), ['redis_lock_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_reservations_released_at'), ['released_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_reservations_reserved_at'), ['reserved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_reservations_schedule_entry_accession_id'), ['schedule_entry_accession_id'], unique=False)

    op.create_table('function_data_outputs',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('data_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('spatial_coordinates_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('data_units', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('measurement_conditions_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('sequence_in_function', sa.Integer(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('measurement_timestamp', sa.DateTime(), nullable=True),
    sa.Column('data_type', sa.Enum('ABSORBANCE_READING', 'FLUORESCENCE_READING', 'LUMINESCENCE_READING', 'OPTICAL_DENSITY', 'TEMPERATURE_READING', 'VOLUME_MEASUREMENT', 'GENERIC_MEASUREMENT', 'PLATE_IMAGE', 'MICROSCOPY_IMAGE', 'CAMERA_SNAPSHOT', 'RAW_DATA_FILE', 'ANALYSIS_REPORT', 'CONFIGURATION_FILE', 'CALCULATED_CONCENTRATION', 'KINETIC_ANALYSIS', 'STATISTICAL_SUMMARY', 'MACHINE_STATUS', 'LIQUID_LEVEL', 'ERROR_LOG', 'UNKNOWN', name='dataoutputtypeenum'), nullable=False),
    sa.Column('spatial_context', sa.Enum('WELL_SPECIFIC', 'PLATE_LEVEL', 'MACHINE_LEVEL', 'DECK_POSITION', 'GLOBAL', name='spatialcontextenum'), nullable=False),
    sa.Column('data_value_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('data_value_numeric', sa.Float(), nullable=True),
    sa.Column('data_value_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_value_binary', sa.LargeBinary(), nullable=True),
    sa.Column('function_call_log_accession_id', sa.Uuid(), nullable=True),
    sa.Column('protocol_run_accession_id', sa.Uuid(), nullable=True),
    sa.Column('machine_accession_id', sa.Uuid(), nullable=True),
    sa.Column('resource_accession_id', sa.Uuid(), nullable=True),
    sa.Column('deck_accession_id', sa.Uuid(), nullable=True),
    sa.Column('derived_from_data_output_accession_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['deck_accession_id'], ['decks.accession_id'], ),
    sa.ForeignKeyConstraint(['derived_from_data_output_accession_id'], ['function_data_outputs.accession_id'], ),
    sa.ForeignKeyConstraint(['function_call_log_accession_id'], ['function_call_logs.accession_id'], ),
    sa.ForeignKeyConstraint(['machine_accession_id'], ['machines.accession_id'], ),
    sa.ForeignKeyConstraint(['protocol_run_accession_id'], ['protocol_runs.accession_id'], ),
    sa.ForeignKeyConstraint(['resource_accession_id'], ['resources.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id')
    )
    with op.batch_alter_table('function_data_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_function_data_outputs_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_data_outputs_data_key'), ['data_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_data_outputs_deck_accession_id'), ['deck_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_data_outputs_derived_from_data_output_accession_id'), ['derived_from_data_output_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_data_outputs_function_call_log_accession_id'), ['function_call_log_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_data_outputs_machine_accession_id'), ['machine_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_data_outputs_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_data_outputs_protocol_run_accession_id'), ['protocol_run_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_data_outputs_resource_accession_id'), ['resource_accession_id'], unique=False)

    op.create_table('schedule_history',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('event_type', sa.Enum('SCHEDULE_CREATED', 'SCHEDULED', 'STATUS_CHANGED', 'EXECUTED', 'COMPLETED', 'FAILED', 'CANCELLED', 'RESCHEDULED', 'CONFLICT', 'TIMEOUT', 'PARTIAL_COMPLETION', 'INTERVENTION_REQUIRED', 'PRIORITY_CHANGED', 'UNKNOWN', name='schedulehistoryeventenum'), nullable=False),
    sa.Column('from_status', sa.Enum('QUEUED', 'RESERVED', 'READY_TO_EXECUTE', 'CELERY_QUEUED', 'EXECUTING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CONFLICT', 'TIMEOUT', name='schedulestatusenum'), nullable=True),
    sa.Column('to_status', sa.Enum('QUEUED', 'RESERVED', 'READY_TO_EXECUTE', 'CELERY_QUEUED', 'EXECUTING', 'COMPLETED', 'FAILED', 'CANCELLED', 'CONFLICT', 'TIMEOUT', name='schedulestatusenum'), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('event_start', sa.DateTime(), nullable=True),
    sa.Column('event_end', sa.DateTime(), nullable=True),
    sa.Column('override_duration_ms', sa.Integer(), nullable=True),
    sa.Column('asset_count', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.Enum('USER', 'API', 'PYLABROBOT', 'CELERY', 'SYSTEM', name='schedulehistoryeventtriggerenum'), nullable=True),
    sa.Column('event_data_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('schedule_entry_accession_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_entry_accession_id'], ['schedule_entries.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id')
    )
    with op.batch_alter_table('schedule_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_history_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_history_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_history_schedule_entry_accession_id'), ['schedule_entry_accession_id'], unique=False)

    op.create_table('state_resolution_log',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('operation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operation_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uncertain_states_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('resolution_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('resolution_type', sa.Enum('CONFIRMED_SUCCESS', 'CONFIRMED_FAILURE', 'PARTIAL', 'ARBITRARY', 'UNKNOWN', name='resolutiontypeenum'), nullable=False),
    sa.Column('resolved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action_taken', sa.Enum('RESUME', 'ABORT', 'RETRY', name='resolutionactionenum'), nullable=False),
    sa.Column('schedule_entry_accession_id', sa.Uuid(), nullable=False),
    sa.Column('protocol_run_accession_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_run_accession_id'], ['protocol_runs.accession_id'], ),
    sa.ForeignKeyConstraint(['schedule_entry_accession_id'], ['schedule_entries.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id')
    )
    with op.batch_alter_table('state_resolution_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_state_resolution_log_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_resolution_log_action_taken'), ['action_taken'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_resolution_log_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_resolution_log_operation_id'), ['operation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_resolution_log_protocol_run_accession_id'), ['protocol_run_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_resolution_log_resolution_type'), ['resolution_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_state_resolution_log_schedule_entry_accession_id'), ['schedule_entry_accession_id'], unique=False)

    op.create_table('well_data_outputs',
    sa.Column('accession_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('properties_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('well_position', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('measurement_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('well_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_value', sa.Float(), nullable=True),
    sa.Column('well_row', sa.Integer(), nullable=False),
    sa.Column('well_column', sa.Integer(), nullable=False),
    sa.Column('well_index', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('function_data_output_accession_id', sa.Uuid(), nullable=True),
    sa.Column('resource_accession_id', sa.Uuid(), nullable=True),
    sa.Column('plate_resource_accession_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['function_data_output_accession_id'], ['function_data_outputs.accession_id'], ),
    sa.ForeignKeyConstraint(['plate_resource_accession_id'], ['resources.accession_id'], ),
    sa.ForeignKeyConstraint(['resource_accession_id'], ['resources.accession_id'], ),
    sa.PrimaryKeyConstraint('accession_id')
    )
    with op.batch_alter_table('well_data_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_well_data_outputs_accession_id'), ['accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_well_data_outputs_function_data_output_accession_id'), ['function_data_output_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_well_data_outputs_measurement_type'), ['measurement_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_well_data_outputs_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_well_data_outputs_plate_resource_accession_id'), ['plate_resource_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_well_data_outputs_resource_accession_id'), ['resource_accession_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_well_data_outputs_well_position'), ['well_position'], unique=False)

    op.create_table('scheduler_metrics_mv',
    sa.Column('metric_timestamp', sa.DateTime(), nullable=False),
    sa.Column('protocols_scheduled', sa.Integer(), nullable=False),
    sa.Column('protocols_completed', sa.Integer(), nullable=False),
    sa.Column('protocols_failed', sa.Integer(), nullable=False),
    sa.Column('protocols_cancelled', sa.Integer(), nullable=False),
    sa.Column('avg_queue_wait_time_ms', sa.Float(), nullable=False),
    sa.Column('avg_execution_time_ms', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('metric_timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler_metrics_mv')
    with op.batch_alter_table('well_data_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_well_data_outputs_well_position'))
        batch_op.drop_index(batch_op.f('ix_well_data_outputs_resource_accession_id'))
        batch_op.drop_index(batch_op.f('ix_well_data_outputs_plate_resource_accession_id'))
        batch_op.drop_index(batch_op.f('ix_well_data_outputs_name'))
        batch_op.drop_index(batch_op.f('ix_well_data_outputs_measurement_type'))
        batch_op.drop_index(batch_op.f('ix_well_data_outputs_function_data_output_accession_id'))
        batch_op.drop_index(batch_op.f('ix_well_data_outputs_accession_id'))

    op.drop_table('well_data_outputs')
    with op.batch_alter_table('state_resolution_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_state_resolution_log_schedule_entry_accession_id'))
        batch_op.drop_index(batch_op.f('ix_state_resolution_log_resolution_type'))
        batch_op.drop_index(batch_op.f('ix_state_resolution_log_protocol_run_accession_id'))
        batch_op.drop_index(batch_op.f('ix_state_resolution_log_operation_id'))
        batch_op.drop_index(batch_op.f('ix_state_resolution_log_name'))
        batch_op.drop_index(batch_op.f('ix_state_resolution_log_action_taken'))
        batch_op.drop_index(batch_op.f('ix_state_resolution_log_accession_id'))

    op.drop_table('state_resolution_log')
    with op.batch_alter_table('schedule_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_history_schedule_entry_accession_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_history_name'))
        batch_op.drop_index(batch_op.f('ix_schedule_history_accession_id'))

    op.drop_table('schedule_history')
    with op.batch_alter_table('function_data_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_function_data_outputs_resource_accession_id'))
        batch_op.drop_index(batch_op.f('ix_function_data_outputs_protocol_run_accession_id'))
        batch_op.drop_index(batch_op.f('ix_function_data_outputs_name'))
        batch_op.drop_index(batch_op.f('ix_function_data_outputs_machine_accession_id'))
        batch_op.drop_index(batch_op.f('ix_function_data_outputs_function_call_log_accession_id'))
        batch_op.drop_index(batch_op.f('ix_function_data_outputs_derived_from_data_output_accession_id'))
        batch_op.drop_index(batch_op.f('ix_function_data_outputs_deck_accession_id'))
        batch_op.drop_index(batch_op.f('ix_function_data_outputs_data_key'))
        batch_op.drop_index(batch_op.f('ix_function_data_outputs_accession_id'))

    op.drop_table('function_data_outputs')
    with op.batch_alter_table('asset_reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_reservations_schedule_entry_accession_id'))
        batch_op.drop_index(batch_op.f('ix_asset_reservations_reserved_at'))
        batch_op.drop_index(batch_op.f('ix_asset_reservations_released_at'))
        batch_op.drop_index(batch_op.f('ix_asset_reservations_redis_lock_key'))
        batch_op.drop_index(batch_op.f('ix_asset_reservations_protocol_run_accession_id'))
        batch_op.drop_index(batch_op.f('ix_asset_reservations_name'))
        batch_op.drop_index(batch_op.f('ix_asset_reservations_is_active'))
        batch_op.drop_index(batch_op.f('ix_asset_reservations_asset_name'))
        batch_op.drop_index(batch_op.f('ix_asset_reservations_accession_id'))

    op.drop_table('asset_reservations')
    with op.batch_alter_table('schedule_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_entries_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_schedule_entries_protocol_run_accession_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_entries_priority'))
        batch_op.drop_index(batch_op.f('ix_schedule_entries_name'))
        batch_op.drop_index(batch_op.f('ix_schedule_entries_execution_started_at'))
        batch_op.drop_index(batch_op.f('ix_schedule_entries_execution_completed_at'))
        batch_op.drop_index(batch_op.f('ix_schedule_entries_celery_task_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_entries_celery_queue_name'))
        batch_op.drop_index(batch_op.f('ix_schedule_entries_accession_id'))

    op.drop_table('schedule_entries')
    with op.batch_alter_table('machine_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_definitions_name'))
        batch_op.drop_index(batch_op.f('ix_machine_definitions_fqn'))
        batch_op.drop_index(batch_op.f('ix_machine_definitions_accession_id'))

    op.drop_table('machine_definitions')
    with op.batch_alter_table('function_call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_function_call_logs_sequence_in_run'))
        batch_op.drop_index(batch_op.f('ix_function_call_logs_protocol_run_accession_id'))
        batch_op.drop_index(batch_op.f('ix_function_call_logs_parent_function_call_log_accession_id'))
        batch_op.drop_index(batch_op.f('ix_function_call_logs_name'))
        batch_op.drop_index(batch_op.f('ix_function_call_logs_function_protocol_definition_accession_id'))
        batch_op.drop_index(batch_op.f('ix_function_call_logs_accession_id'))

    op.drop_table('function_call_logs')
    with op.batch_alter_table('protocol_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protocol_runs_top_level_protocol_definition_accession_id'))
        batch_op.drop_index(batch_op.f('ix_protocol_runs_status'))
        batch_op.drop_index(batch_op.f('ix_protocol_runs_previous_accession_id'))
        batch_op.drop_index(batch_op.f('ix_protocol_runs_name'))
        batch_op.drop_index(batch_op.f('ix_protocol_runs_accession_id'))

    op.drop_table('protocol_runs')
    with op.batch_alter_table('protocol_asset_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protocol_asset_requirements_type_hint_str'))
        batch_op.drop_index(batch_op.f('ix_protocol_asset_requirements_required_plr_category'))
        batch_op.drop_index(batch_op.f('ix_protocol_asset_requirements_protocol_definition_accession_id'))
        batch_op.drop_index(batch_op.f('ix_protocol_asset_requirements_name'))
        batch_op.drop_index(batch_op.f('ix_protocol_asset_requirements_fqn'))
        batch_op.drop_index(batch_op.f('ix_protocol_asset_requirements_actual_type_str'))
        batch_op.drop_index(batch_op.f('ix_protocol_asset_requirements_accession_id'))

    op.drop_table('protocol_asset_requirements')
    with op.batch_alter_table('parameter_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parameter_definitions_type_hint'))
        batch_op.drop_index(batch_op.f('ix_parameter_definitions_protocol_definition_accession_id'))
        batch_op.drop_index(batch_op.f('ix_parameter_definitions_name'))
        batch_op.drop_index(batch_op.f('ix_parameter_definitions_fqn'))
        batch_op.drop_index(batch_op.f('ix_parameter_definitions_accession_id'))

    op.drop_table('parameter_definitions')
    with op.batch_alter_table('machine_backend_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_backend_definitions_name'))
        batch_op.drop_index(batch_op.f('ix_machine_backend_definitions_fqn'))
        batch_op.drop_index(batch_op.f('ix_machine_backend_definitions_accession_id'))

    op.drop_table('machine_backend_definitions')
    with op.batch_alter_table('machine_frontend_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_frontend_definitions_name'))
        batch_op.drop_index(batch_op.f('ix_machine_frontend_definitions_fqn'))
        batch_op.drop_index(batch_op.f('ix_machine_frontend_definitions_accession_id'))

    op.drop_table('machine_frontend_definitions')
    with op.batch_alter_table('function_protocol_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_function_protocol_definitions_source_repository_accession_id'))
        batch_op.drop_index(batch_op.f('ix_function_protocol_definitions_source_file_path'))
        batch_op.drop_index(batch_op.f('ix_function_protocol_definitions_name'))
        batch_op.drop_index(batch_op.f('ix_function_protocol_definitions_module_name'))
        batch_op.drop_index(batch_op.f('ix_function_protocol_definitions_is_top_level'))
        batch_op.drop_index(batch_op.f('ix_function_protocol_definitions_function_name'))
        batch_op.drop_index(batch_op.f('ix_function_protocol_definitions_fqn'))
        batch_op.drop_index(batch_op.f('ix_function_protocol_definitions_file_system_source_accession_id'))
        batch_op.drop_index(batch_op.f('ix_function_protocol_definitions_deprecated'))
        batch_op.drop_index(batch_op.f('ix_function_protocol_definitions_commit_hash'))
        batch_op.drop_index(batch_op.f('ix_function_protocol_definitions_category'))
        batch_op.drop_index(batch_op.f('ix_function_protocol_definitions_accession_id'))

    op.drop_table('function_protocol_definitions')
    with op.batch_alter_table('deck_position_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deck_position_definitions_position_accession_id'))
        batch_op.drop_index(batch_op.f('ix_deck_position_definitions_name'))
        batch_op.drop_index(batch_op.f('ix_deck_position_definitions_deck_type_id'))
        batch_op.drop_index(batch_op.f('ix_deck_position_definitions_accession_id'))

    op.drop_table('deck_position_definitions')
    with op.batch_alter_table('workcells', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workcells_name'))
        batch_op.drop_index(batch_op.f('ix_workcells_fqn'))
        batch_op.drop_index(batch_op.f('ix_workcells_accession_id'))

    op.drop_table('workcells')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_accession_id'))

    op.drop_table('users')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_name'))
        batch_op.drop_index(batch_op.f('ix_resources_location'))
        batch_op.drop_index(batch_op.f('ix_resources_fqn'))
        batch_op.drop_index(batch_op.f('ix_resources_accession_id'))

    op.drop_table('resources')
    with op.batch_alter_table('resource_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_definitions_well_volume_ul'))
        batch_op.drop_index(batch_op.f('ix_resource_definitions_vendor'))
        batch_op.drop_index(batch_op.f('ix_resource_definitions_tip_volume_ul'))
        batch_op.drop_index(batch_op.f('ix_resource_definitions_plate_type'))
        batch_op.drop_index(batch_op.f('ix_resource_definitions_num_items'))
        batch_op.drop_index(batch_op.f('ix_resource_definitions_name'))
        batch_op.drop_index(batch_op.f('ix_resource_definitions_fqn'))
        batch_op.drop_index(batch_op.f('ix_resource_definitions_deck_definition_accession_id'))
        batch_op.drop_index(batch_op.f('ix_resource_definitions_asset_requirement_accession_id'))
        batch_op.drop_index(batch_op.f('ix_resource_definitions_accession_id'))

    op.drop_table('resource_definitions')
    with op.batch_alter_table('protocol_source_repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protocol_source_repositories_name'))
        batch_op.drop_index(batch_op.f('ix_protocol_source_repositories_git_url'))
        batch_op.drop_index(batch_op.f('ix_protocol_source_repositories_accession_id'))

    op.drop_table('protocol_source_repositories')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_serial_number'))
        batch_op.drop_index(batch_op.f('ix_machines_name'))
        batch_op.drop_index(batch_op.f('ix_machines_location'))
        batch_op.drop_index(batch_op.f('ix_machines_last_seen_online'))
        batch_op.drop_index(batch_op.f('ix_machines_fqn'))
        batch_op.drop_index(batch_op.f('ix_machines_accession_id'))

    op.drop_table('machines')
    with op.batch_alter_table('file_system_protocol_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_system_protocol_sources_name'))
        batch_op.drop_index(batch_op.f('ix_file_system_protocol_sources_accession_id'))

    op.drop_table('file_system_protocol_sources')
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decks_name'))
        batch_op.drop_index(batch_op.f('ix_decks_location'))
        batch_op.drop_index(batch_op.f('ix_decks_fqn'))
        batch_op.drop_index(batch_op.f('ix_decks_accession_id'))

    op.drop_table('decks')
    with op.batch_alter_table('deck_definition_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deck_definition_catalog_fqn'))
        batch_op.drop_index(batch_op.f('ix_deck_definition_catalog_accession_id'))

    op.drop_table('deck_definition_catalog')
    # ### end Alembic commands ###
