// Mocks generated by Mockito 5.4.5 from annotations
// in praxis_lab_management/test/mocks/mock_services.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:praxis_lab_management/src/data/models/deck_layout_orm.dart'
    as _i5;
import 'package:praxis_lab_management/src/data/models/labware_definition_catalog_orm.dart'
    as _i3;
import 'package:praxis_lab_management/src/data/models/labware_instance_orm.dart'
    as _i4;
import 'package:praxis_lab_management/src/data/models/managed_device_orm.dart'
    as _i2;
import 'package:praxis_lab_management/src/data/models/protocol/deck_layout.dart'
    as _i6;
import 'package:praxis_lab_management/src/data/services/asset_api_service.dart'
    as _i7;
import 'package:praxis_lab_management/src/data/services/workcell_api_service.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeManagedDeviceOrm_0 extends _i1.SmartFake
    implements _i2.ManagedDeviceOrm {
  _FakeManagedDeviceOrm_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLabwareDefinitionCatalogOrm_1 extends _i1.SmartFake
    implements _i3.LabwareDefinitionCatalogOrm {
  _FakeLabwareDefinitionCatalogOrm_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLabwareInstanceOrm_2 extends _i1.SmartFake
    implements _i4.LabwareInstanceOrm {
  _FakeLabwareInstanceOrm_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeckLayoutOrm_3 extends _i1.SmartFake implements _i5.DeckLayoutOrm {
  _FakeDeckLayoutOrm_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeckLayout_4 extends _i1.SmartFake implements _i6.DeckLayout {
  _FakeDeckLayout_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AssetApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAssetApiService extends _i1.Mock implements _i7.AssetApiService {
  MockAssetApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i2.ManagedDeviceOrm>> getDevices() =>
      (super.noSuchMethod(
            Invocation.method(#getDevices, []),
            returnValue: _i8.Future<List<_i2.ManagedDeviceOrm>>.value(
              <_i2.ManagedDeviceOrm>[],
            ),
          )
          as _i8.Future<List<_i2.ManagedDeviceOrm>>);

  @override
  _i8.Future<_i2.ManagedDeviceOrm> createDevice(_i2.ManagedDeviceOrm? device) =>
      (super.noSuchMethod(
            Invocation.method(#createDevice, [device]),
            returnValue: _i8.Future<_i2.ManagedDeviceOrm>.value(
              _FakeManagedDeviceOrm_0(
                this,
                Invocation.method(#createDevice, [device]),
              ),
            ),
          )
          as _i8.Future<_i2.ManagedDeviceOrm>);

  @override
  _i8.Future<_i2.ManagedDeviceOrm> getDeviceById(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceById, [deviceId]),
            returnValue: _i8.Future<_i2.ManagedDeviceOrm>.value(
              _FakeManagedDeviceOrm_0(
                this,
                Invocation.method(#getDeviceById, [deviceId]),
              ),
            ),
          )
          as _i8.Future<_i2.ManagedDeviceOrm>);

  @override
  _i8.Future<_i2.ManagedDeviceOrm> updateDevice(
    String? deviceId,
    _i2.ManagedDeviceOrm? device,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDevice, [deviceId, device]),
            returnValue: _i8.Future<_i2.ManagedDeviceOrm>.value(
              _FakeManagedDeviceOrm_0(
                this,
                Invocation.method(#updateDevice, [deviceId, device]),
              ),
            ),
          )
          as _i8.Future<_i2.ManagedDeviceOrm>);

  @override
  _i8.Future<void> deleteDevice(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDevice, [deviceId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> connectDevice(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#connectDevice, [deviceId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> initializeDevice(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#initializeDevice, [deviceId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> disconnectDevice(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectDevice, [deviceId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i3.LabwareDefinitionCatalogOrm>> getLabwareDefinitions() =>
      (super.noSuchMethod(
            Invocation.method(#getLabwareDefinitions, []),
            returnValue:
                _i8.Future<List<_i3.LabwareDefinitionCatalogOrm>>.value(
                  <_i3.LabwareDefinitionCatalogOrm>[],
                ),
          )
          as _i8.Future<List<_i3.LabwareDefinitionCatalogOrm>>);

  @override
  _i8.Future<_i3.LabwareDefinitionCatalogOrm> createLabwareDefinition(
    _i3.LabwareDefinitionCatalogOrm? labwareDefinition,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createLabwareDefinition, [labwareDefinition]),
            returnValue: _i8.Future<_i3.LabwareDefinitionCatalogOrm>.value(
              _FakeLabwareDefinitionCatalogOrm_1(
                this,
                Invocation.method(#createLabwareDefinition, [
                  labwareDefinition,
                ]),
              ),
            ),
          )
          as _i8.Future<_i3.LabwareDefinitionCatalogOrm>);

  @override
  _i8.Future<_i3.LabwareDefinitionCatalogOrm> updateLabwareDefinition(
    String? labwareDefinitionId,
    _i3.LabwareDefinitionCatalogOrm? labwareDefinition,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLabwareDefinition, [
              labwareDefinitionId,
              labwareDefinition,
            ]),
            returnValue: _i8.Future<_i3.LabwareDefinitionCatalogOrm>.value(
              _FakeLabwareDefinitionCatalogOrm_1(
                this,
                Invocation.method(#updateLabwareDefinition, [
                  labwareDefinitionId,
                  labwareDefinition,
                ]),
              ),
            ),
          )
          as _i8.Future<_i3.LabwareDefinitionCatalogOrm>);

  @override
  _i8.Future<void> deleteLabwareDefinition(String? labwareDefinitionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLabwareDefinition, [labwareDefinitionId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i4.LabwareInstanceOrm>> getLabwareInstances() =>
      (super.noSuchMethod(
            Invocation.method(#getLabwareInstances, []),
            returnValue: _i8.Future<List<_i4.LabwareInstanceOrm>>.value(
              <_i4.LabwareInstanceOrm>[],
            ),
          )
          as _i8.Future<List<_i4.LabwareInstanceOrm>>);

  @override
  _i8.Future<_i4.LabwareInstanceOrm> createLabwareInstance(
    _i4.LabwareInstanceOrm? labwareInstance,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createLabwareInstance, [labwareInstance]),
            returnValue: _i8.Future<_i4.LabwareInstanceOrm>.value(
              _FakeLabwareInstanceOrm_2(
                this,
                Invocation.method(#createLabwareInstance, [labwareInstance]),
              ),
            ),
          )
          as _i8.Future<_i4.LabwareInstanceOrm>);

  @override
  _i8.Future<_i4.LabwareInstanceOrm> getLabwareInstanceById(
    String? instanceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLabwareInstanceById, [instanceId]),
            returnValue: _i8.Future<_i4.LabwareInstanceOrm>.value(
              _FakeLabwareInstanceOrm_2(
                this,
                Invocation.method(#getLabwareInstanceById, [instanceId]),
              ),
            ),
          )
          as _i8.Future<_i4.LabwareInstanceOrm>);

  @override
  _i8.Future<_i4.LabwareInstanceOrm> updateLabwareInstance(
    String? instanceId,
    _i4.LabwareInstanceOrm? labwareInstance,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLabwareInstance, [
              instanceId,
              labwareInstance,
            ]),
            returnValue: _i8.Future<_i4.LabwareInstanceOrm>.value(
              _FakeLabwareInstanceOrm_2(
                this,
                Invocation.method(#updateLabwareInstance, [
                  instanceId,
                  labwareInstance,
                ]),
              ),
            ),
          )
          as _i8.Future<_i4.LabwareInstanceOrm>);

  @override
  _i8.Future<void> deleteLabwareInstance(String? instanceId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLabwareInstance, [instanceId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i5.DeckLayoutOrm>> getDeckLayouts() =>
      (super.noSuchMethod(
            Invocation.method(#getDeckLayouts, []),
            returnValue: _i8.Future<List<_i5.DeckLayoutOrm>>.value(
              <_i5.DeckLayoutOrm>[],
            ),
          )
          as _i8.Future<List<_i5.DeckLayoutOrm>>);

  @override
  _i8.Future<_i5.DeckLayoutOrm> createDeckLayout(
    _i5.DeckLayoutOrm? deckLayout,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createDeckLayout, [deckLayout]),
            returnValue: _i8.Future<_i5.DeckLayoutOrm>.value(
              _FakeDeckLayoutOrm_3(
                this,
                Invocation.method(#createDeckLayout, [deckLayout]),
              ),
            ),
          )
          as _i8.Future<_i5.DeckLayoutOrm>);

  @override
  _i8.Future<_i5.DeckLayoutOrm> getDeckLayoutById(String? deckLayoutId) =>
      (super.noSuchMethod(
            Invocation.method(#getDeckLayoutById, [deckLayoutId]),
            returnValue: _i8.Future<_i5.DeckLayoutOrm>.value(
              _FakeDeckLayoutOrm_3(
                this,
                Invocation.method(#getDeckLayoutById, [deckLayoutId]),
              ),
            ),
          )
          as _i8.Future<_i5.DeckLayoutOrm>);

  @override
  _i8.Future<_i5.DeckLayoutOrm> updateDeckLayout(
    String? deckLayoutId,
    _i5.DeckLayoutOrm? deckLayout,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDeckLayout, [deckLayoutId, deckLayout]),
            returnValue: _i8.Future<_i5.DeckLayoutOrm>.value(
              _FakeDeckLayoutOrm_3(
                this,
                Invocation.method(#updateDeckLayout, [
                  deckLayoutId,
                  deckLayout,
                ]),
              ),
            ),
          )
          as _i8.Future<_i5.DeckLayoutOrm>);

  @override
  _i8.Future<void> deleteDeckLayout(String? deckLayoutId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDeckLayout, [deckLayoutId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [WorkcellApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkcellApiService extends _i1.Mock
    implements _i9.WorkcellApiService {
  MockWorkcellApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.DeckLayout> fetchDeckState(String? workcellId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDeckState, [workcellId]),
            returnValue: _i8.Future<_i6.DeckLayout>.value(
              _FakeDeckLayout_4(
                this,
                Invocation.method(#fetchDeckState, [workcellId]),
              ),
            ),
          )
          as _i8.Future<_i6.DeckLayout>);

  @override
  _i8.Stream<dynamic> subscribeToWorkcellUpdates(String? workcellId) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToWorkcellUpdates, [workcellId]),
            returnValue: _i8.Stream<dynamic>.empty(),
          )
          as _i8.Stream<dynamic>);

  @override
  _i8.Future<void> closeWebSocket() =>
      (super.noSuchMethod(
            Invocation.method(#closeWebSocket, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
