#!/usr/bin/env python3
"""Inject the D1 shell-side ``praxis_git_sha`` value into a built
``lab/index.html`` -- the ONLY home for the D1 expected value (ADR
``.praxia/docs/decisions/260817_repl-layout-and-delivery-mechanism.md``
Sec 2.3), deliberately kept OUTSIDE the JupyterLite fetched-asset set.

This script never rewrites ``shell/praxis-shell.js`` (tracked source, never
mutated -- see that file's own docstring for why). It rewrites the
GENERATED ``lab/index.html`` only, inserting a small inline
``<script>window.PRAXIS_GIT_SHA = "...";</script>`` immediately before a
``<script src="...praxis-shell.js">`` include, between HTML comment markers
so a second run replaces the block instead of duplicating it.

``--dev`` writes the literal sentinel ``"dev"`` -- pairs with
``build_manifest.py --dev``. The D1 compare (``stages.assert_praxis_git_sha``)
is skipped only when BOTH sides read ``"dev"``, which falls out of plain
string equality rather than being special-cased anywhere.

``build_repl.py`` (Phase 5, not yet written) is expected to call this script
as a post-processing step after ``jupyter lite build`` produces
``dist/lab/index.html``, and to copy ``shell/praxis-shell.js`` into
``dist/shell/praxis-shell.js`` (the default ``--script-src`` below assumes
that relative layout) before this script runs.

The injection point is located by the ``id="jupyter-lite-main"`` anchor that
JupyterLite's own generated ``index.html`` carries, NOT by a generic
``</head>``/``</body>`` fallback. A silent fallback to some other insertion
point would produce a site where D1 simply never fires -- a build that looks
identical to a correctly-injected one until the first genuine staleness
incident. So a missing or duplicated anchor fails loud, with context, rather
than falling back.

``--check`` verifies an already-built ``dist/`` was injected correctly
WITHOUT modifying it -- this is what CI calls. It exits nonzero if the
anchor is missing/duplicated, the injected block is absent, the injected
``praxis_git_sha`` is empty, or the shell script the block's ``<script
src=...>`` points at is not actually on disk. It accepts the literal "dev"
sentinel as a valid (non-empty) value -- ``--check`` verifies STRUCTURE, not
that a build is a "real" (non-dev) build, so it stays usable against dev-loop
output produced by ``inject_shell.py --dev`` / ``build_manifest.py --dev``.

House rules: uv-run only, argparse + logging, narrow runs, fail loud.
"""

from __future__ import annotations

import argparse
import logging
import os
import re
import subprocess
import tempfile
from pathlib import Path

logger = logging.getLogger("inject_shell")

_THIS_FILE = Path(__file__).resolve()
DEFAULT_WEB_REPL_ROOT = _THIS_FILE.parents[1]
DEFAULT_REPO_ROOT = _THIS_FILE.parents[2]
DEFAULT_DIST_REL = Path("dist")
# One shared shell copy at <out>/shell/, referenced from every entry's
# index.html one directory down. A per-entry copy would work too, but D1's
# whole point is that ONE expected value exists outside the asset set --
# N copies is N chances for them to drift apart.
DEFAULT_SCRIPT_SRC = "../shell/praxis-shell.js"

DEV_SENTINEL = "dev"

_BEGIN_MARKER = "<!-- PRAXIS-SHELL-INJECT:BEGIN (D1, ADR Sec 2.3 -- generated by inject_shell.py, do not hand-edit) -->"
_END_MARKER = "<!-- PRAXIS-SHELL-INJECT:END -->"

# The insertion-point anchor. JupyterLite's generated `index.html` carries
# this id on the element the app shell mounts into. Locating the injection
# point by this anchor -- rather than a generic </head>/</body> fallback --
# is the whole point of this assertion: an absent or duplicated anchor must
# fail the build loud, not silently degrade to "inject it somewhere".
_ANCHOR_ID = "jupyter-lite-main"
_ANCHOR_PATTERN = re.compile(r'id=["\']' + re.escape(_ANCHOR_ID) + r'["\']')

# Pulled back out of an already-injected block by --check. Matches exactly
# what `_render_block` emits below.
_SHA_ASSIGN_PATTERN = re.compile(r'window\.PRAXIS_GIT_SHA\s*=\s*"([^"]*)"')
_SCRIPT_SRC_PATTERN = re.compile(r'<script src="([^"]*)"></script>')


class InjectError(RuntimeError):
    """Raised for any condition that must fail shell injection loudly."""


def _find_anchor_tag_start(html: str) -> int:
    """Return the index of the ``<`` that opens the anchor's tag.

    Raises ``InjectError`` (with surrounding context) if the anchor is
    absent or appears more than once -- an ambiguous or missing anchor must
    never be resolved by guessing.
    """
    matches = list(_ANCHOR_PATTERN.finditer(html))

    if not matches:
        raise InjectError(
            f'anchor id="{_ANCHOR_ID}" not found in target HTML -- refusing '
            "to fall back to some other insertion point (e.g. </head> or "
            "</body>). That fallback is exactly what would make a build "
            "where D1 silently never fires indistinguishable from a "
            "correctly-injected one."
        )

    if len(matches) > 1:
        contexts = []
        for m in matches:
            lo = max(0, m.start() - 60)
            hi = min(len(html), m.end() + 60)
            contexts.append(f"  ...{html[lo:hi]!r}...")
        raise InjectError(
            f'anchor id="{_ANCHOR_ID}" appears {len(matches)} times in '
            "target HTML -- the insertion point is ambiguous, refusing to "
            "guess which one. Occurrences:\n" + "\n".join(contexts)
        )

    tag_start = html.rfind("<", 0, matches[0].start())
    if tag_start == -1:
        raise InjectError(
            f'anchor id="{_ANCHOR_ID}" matched but has no preceding "<" -- '
            "the match is not inside a real HTML tag; refusing to guess an "
            "insertion point."
        )
    return tag_start


def _git_head(repo_root: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(repo_root), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def _render_block(sha: str, script_src: str) -> str:
    # json-safe-enough: sha is either 40 hex chars or the literal "dev", and
    # script_src is a build-controlled relative path -- neither ever
    # contains a quote or `</script>`, but escape defensively anyway rather
    # than trust that invariant forever.
    safe_sha = sha.replace("\\", "\\\\").replace('"', '\\"').replace("</", "<\\/")
    safe_src = script_src.replace('"', "&quot;")
    return (
        f"{_BEGIN_MARKER}\n"
        f'<script>window.PRAXIS_GIT_SHA = "{safe_sha}";</script>\n'
        f'<script src="{safe_src}"></script>\n'
        f"{_END_MARKER}"
    )


def inject(html: str, sha: str, script_src: str) -> str:
    """Return *html* with the injected block inserted (or replaced, if a
    previous injection's markers are already present), positioned by the
    ``id="jupyter-lite-main"`` anchor (see ``_find_anchor_tag_start``).

    The anchor is asserted unconditionally -- even on a replace of an
    existing block -- because a corrupted or duplicated anchor makes the
    target suspect regardless of whether markers are already present.

    Fails loud (``InjectError``) if the anchor is absent, duplicated, or (on
    a replace) the markers are mismatched -- a silent no-op here means the
    page ships without D1 coverage and nobody would know until a staleness
    incident went undetected.
    """
    anchor_start = _find_anchor_tag_start(html)
    block = _render_block(sha, script_src)

    if _BEGIN_MARKER in html:
        if _END_MARKER not in html:
            raise InjectError(
                "found the injection BEGIN marker without a matching END "
                "marker -- the target file is corrupted or was hand-edited "
                "inside a previously-injected block; refusing to guess."
            )
        start = html.index(_BEGIN_MARKER)
        end = html.index(_END_MARKER) + len(_END_MARKER)
        return html[:start] + block + html[end:]

    return html[:anchor_start] + block + "\n" + html[anchor_start:]


def _extract_injected_block(html: str) -> str:
    if _BEGIN_MARKER not in html or _END_MARKER not in html:
        raise InjectError(
            "no PRAXIS-SHELL-INJECT block found -- inject_shell.py has not "
            "run against this file (or --dev/real-mode markers were "
            "stripped)."
        )
    start = html.index(_BEGIN_MARKER)
    end = html.index(_END_MARKER) + len(_END_MARKER)
    return html[start:end]


def check(target: Path, default_script_src: str) -> None:
    """Verify *target* was injected correctly, WITHOUT modifying it.

    Raises ``InjectError`` (never returns falsy -- callers should treat any
    return as PASS) if:
      * the anchor is absent or duplicated,
      * no injected block is present,
      * the injected ``praxis_git_sha`` is missing or empty, or
      * the shell script the block's ``<script src=...>`` names is not
        actually present on disk (resolved relative to *target*'s
        directory, matching how a browser would resolve it).

    The literal ``"dev"`` sentinel passes the sha check -- this verifies
    STRUCTURE (the injection happened and points at a real file), not that
    the build is a "real" (non-dev) one. That is `assert_praxis_git_sha`'s
    job at boot, not this script's.
    """
    if not target.is_file():
        raise InjectError(f"{target} does not exist -- nothing to check.")

    html = target.read_text()

    _find_anchor_tag_start(html)  # raises with context if missing/duplicated

    block = _extract_injected_block(html)

    sha_match = _SHA_ASSIGN_PATTERN.search(block)
    if sha_match is None or not sha_match.group(1):
        raise InjectError(
            f"{target}: injected block found but no non-empty "
            "window.PRAXIS_GIT_SHA assignment could be parsed out of it."
        )
    sha = sha_match.group(1)

    src_match = _SCRIPT_SRC_PATTERN.search(block)
    script_src = src_match.group(1) if src_match is not None else default_script_src
    shell_path = (target.parent / script_src).resolve()
    if not shell_path.is_file():
        raise InjectError(
            f'{target}: injected block references shell script src="'
            f"{script_src}\" ({shell_path}), which does not exist on disk."
        )

    logger.info(
        "check OK: %s -- anchor present exactly once, praxis_git_sha=%s, "
        "shell script found at %s",
        target,
        sha,
        shell_path,
    )


def write_atomic(text: str, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=".index-", suffix=".html.tmp", dir=str(dest.parent))
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "w") as f:
            f.write(text)
            f.flush()
            os.fsync(f.fileno())
        os.chmod(tmp_path, 0o644)  # mkstemp defaults to 0600; this is served, not secret
        os.replace(tmp_path, dest)  # atomic
    except BaseException:
        tmp_path.unlink(missing_ok=True)
        raise


def discover_targets(dist_root: Path) -> list[Path]:
    """Every ``<dist>/<entry>/index.html`` carrying the injection anchor.

    JupyterLite emits one entry per app (lab, repl, notebooks, consoles,
    edit, tree). Injecting only ``lab`` left ``repl`` -- the entry whose
    ``?code=&execute=1`` the smoke harness drives -- with no shell at all,
    so D1 could only ever fail closed there. Sorted for determinism.
    """
    if not dist_root.is_dir():
        return []
    found = []
    for candidate in sorted(dist_root.glob("*/index.html")):
        try:
            if _ANCHOR_PATTERN.search(candidate.read_text()):
                found.append(candidate.resolve())
        except OSError:
            continue
    return found


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify an already-built target was injected correctly, "
        "WITHOUT modifying it. Exit nonzero if the anchor is missing/"
        "duplicated, the injected block is absent, praxis_git_sha is "
        "empty, or the referenced shell script is not on disk. This is "
        "what CI calls. Mutually exclusive with --dev/--sha, which only "
        "apply to the write path.",
    )
    parser.add_argument(
        "--dev",
        action="store_true",
        help='Inject praxis_git_sha = "dev" instead of the real superproject '
        "HEAD sha -- pairs with build_manifest.py --dev.",
    )
    parser.add_argument(
        "--sha",
        default=None,
        help="Explicit sha to inject, overriding both --dev and the computed "
        "git HEAD (testing only -- e.g. to construct a deliberate D1 mismatch).",
    )
    parser.add_argument(
        "--target",
        type=Path,
        action="append",
        default=None,
        help="HTML file to inject into. Repeatable. Default: EVERY "
        "<web-repl-root>/dist/*/index.html that carries the anchor -- the "
        "JupyterLite build emits several app entries (lab, repl, notebooks, "
        "consoles, edit, tree) and injecting only one leaves D1 unable to "
        "fire on the others, which reads as a boot failure rather than a "
        "missing injection.",
    )
    parser.add_argument(
        "--script-src",
        default=DEFAULT_SCRIPT_SRC,
        help=f"src= for the praxis-shell.js <script> tag (default: {DEFAULT_SCRIPT_SRC}).",
    )
    parser.add_argument(
        "--web-repl-root",
        type=Path,
        default=DEFAULT_WEB_REPL_ROOT,
        help="Override web-repl/ root (testing only).",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=DEFAULT_REPO_ROOT,
        help="Override superproject root used for `git rev-parse HEAD` (testing only).",
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="Debug-level logging.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s %(name)s: %(message)s",
    )

    web_repl_root = args.web_repl_root.resolve()
    if args.target:
        targets = [t.resolve() for t in args.target]
    else:
        targets = discover_targets(web_repl_root / DEFAULT_DIST_REL)
        if not targets:
            logger.error(
                "no dist/*/index.html carrying anchor id=\"%s\" found under %s -- "
                "run build_repl.py before inject_shell.py.",
                _ANCHOR_ID,
                web_repl_root / DEFAULT_DIST_REL,
            )
            return 1

    if args.check:
        if args.dev or args.sha is not None:
            logger.error("--check is mutually exclusive with --dev/--sha (write-path-only flags).")
            return 1
        failed = 0
        for target in targets:
            try:
                check(target, args.script_src)
            except InjectError as exc:
                logger.error("%s", exc)
                failed += 1
        if failed:
            logger.error("%d/%d target(s) failed --check.", failed, len(targets))
            return 1
        logger.info("all %d target(s) OK", len(targets))
        return 0

    if args.sha is not None:
        sha = args.sha
    elif args.dev:
        sha = DEV_SENTINEL
    else:
        sha = _git_head(args.repo_root.resolve())

    for target in targets:
        if not target.is_file():
            logger.error(
                "%s does not exist -- run `jupyter lite build` (via build_repl.py, "
                "Phase 5) before inject_shell.py.",
                target,
            )
            return 1
        try:
            original = target.read_text()
            injected = inject(original, sha, args.script_src)
            write_atomic(injected, target)
        except InjectError as exc:
            logger.error("%s", exc)
            return 1
        logger.info("injected praxis_git_sha=%s into %s", sha, target)

    logger.info("injected %d target(s)", len(targets))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
