#!/usr/bin/env python3
"""Inject the praxis branding <head> block into every built ``index.html``.

Companion to -- deliberately NOT part of -- ``inject_shell.py``. That script's
``--check`` is the D1 staleness gate (ADR Sec 2.3); folding cosmetic branding
into it would mean a purely visual regression could turn the integrity gate
red, and vice versa. Two concerns, two markers, two ``--check`` modes.

What it does to each target:

* inserts ``<link rel="stylesheet">`` for ``assets/theme/praxis-theme.css`` and
  ``<link rel="icon">`` for ``assets/theme/praxis-favicon.svg``, between
  ``PRAXIS-BRAND-INJECT`` markers so a second run replaces rather than
  duplicates;
* rewrites ``<title>``. This CANNOT live inside the marker block -- the
  generated HTML already carries a ``<title>`` and a second one is invalid, so
  the existing element is edited in place instead.

Two target classes, both handled explicitly (no silent fallback):

1. **App entries** -- ``dist/<app>/index.html``, located by the same
   ``id="jupyter-lite-main"`` anchor ``inject_shell.py`` uses. Asset prefix
   ``../assets/theme/``.
2. **The root redirect shell** -- ``dist/index.html``, which carries NO anchor
   (verified: 0 occurrences). Located by ``</head>``. Asset prefix
   ``./assets/theme/``. It is branded because it is the page a visitor to the
   deployed site actually lands on, so it owns the first favicon and title the
   browser ever sees.

Anything that is neither -- an anchor that is missing from an app entry, or
duplicated -- fails loud rather than resolving by guess.

``--check`` verifies an already-built ``dist/`` WITHOUT modifying it, and is
what CI calls. It fails if the block is absent, the title was not rewritten, or
a referenced asset is not actually on disk (a live <link> to a 404 is the exact
failure this is here to catch).

House rules: uv-run only, argparse + logging, fail loud.
"""

from __future__ import annotations

import argparse
import logging
import re
import sys
from pathlib import Path

logger = logging.getLogger("inject_branding")

_THIS_FILE = Path(__file__).resolve()
DEFAULT_WEB_REPL_ROOT = _THIS_FILE.parents[1]
DEFAULT_DIST_REL = Path("dist")

DEFAULT_TITLE = "praxis REPL"

THEME_CSS_REL = "assets/theme/praxis-theme.css"
FAVICON_REL = "assets/theme/praxis-favicon.svg"

_BEGIN_MARKER = (
  "<!-- PRAXIS-BRAND-INJECT:BEGIN (generated by inject_branding.py, do not hand-edit) -->"
)
_END_MARKER = "<!-- PRAXIS-BRAND-INJECT:END -->"

_ANCHOR_ID = "jupyter-lite-main"
_ANCHOR_PATTERN = re.compile(r'id=["\']' + re.escape(_ANCHOR_ID) + r'["\']')
_TITLE_PATTERN = re.compile(r"<title>(.*?)</title>", re.IGNORECASE | re.DOTALL)
_HEAD_CLOSE_PATTERN = re.compile(r"</head>", re.IGNORECASE)
_HREF_PATTERN = re.compile(r'href="([^"]+)"')


class BrandError(RuntimeError):
  """Raised when injection or verification fails. Always fatal."""


def _find_app_anchor(html: str) -> int:
  """Index of the ``<`` opening the anchor tag in an app entry."""
  matches = list(_ANCHOR_PATTERN.finditer(html))
  if not matches:
    raise BrandError(
      f'anchor id="{_ANCHOR_ID}" not found -- refusing to fall back to some other '
      "insertion point, because a build where branding silently never applied would "
      "look identical to a correctly-branded one."
    )
  if len(matches) > 1:
    raise BrandError(
      f'anchor id="{_ANCHOR_ID}" appears {len(matches)} times -- insertion point is '
      "ambiguous, refusing to guess."
    )
  tag_start = html.rfind("<", 0, matches[0].start())
  if tag_start == -1:
    raise BrandError(f'anchor id="{_ANCHOR_ID}" matched outside any tag -- refusing to guess.')
  return tag_start


def _find_head_close(html: str) -> int:
  """Index of ``</head>`` in the anchor-less root shell."""
  matches = list(_HEAD_CLOSE_PATTERN.finditer(html))
  if not matches:
    raise BrandError("root shell has no </head> -- refusing to guess an insertion point.")
  return matches[0].start()


def _escape(text: str) -> str:
  return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def render_block(prefix: str, *, title: str | None = None) -> str:
  """The marker-delimited <head> fragment for one asset prefix.

  *title* is emitted INSIDE the block only for a page that has no <title> of
  its own -- see ``inject``. Pages that already have one get it rewritten in
  place instead, because two <title> elements is invalid HTML.
  """
  lines = [f"{_BEGIN_MARKER}\n"]
  if title is not None:
    lines.append(f"<title>{_escape(title)}</title>\n")
  lines.extend([
    f'<link rel="stylesheet" href="{prefix}{THEME_CSS_REL}">\n',
    f'<link rel="icon" type="image/svg+xml" href="{prefix}{FAVICON_REL}">\n',
    f"{_END_MARKER}",
  ])
  return "".join(lines)


def _replace_title(html: str, title: str) -> str:
  if not _TITLE_PATTERN.search(html):
    raise BrandError("no <title> element found -- refusing to invent one.")
  return _TITLE_PATTERN.sub(f"<title>{_escape(title)}</title>", html, count=1)


def inject(html: str, prefix: str, title: str, *, anchored: bool) -> str:
  """Return *html* with the branding block inserted/replaced and title rewritten.

  Title handling differs by target class, deliberately:

  * **App entries** always ship a <title> (JupyterLite writes "JupyterLite" /
    "REPLite"), so it is rewritten in place and its ABSENCE is an error --
    that would mean the generated HTML changed shape and the rest of this
    script's assumptions are suspect.
  * **The root redirect shell** ships with NO <title> at all (verified against
    a real build). Since it is the page a visitor to the deployed site lands
    on, it gets one emitted inside the marker block rather than being left
    advertising a bare URL.
  """
  # Strip any previous block FIRST. The root shell's <title> lives inside the
  # block, so deciding "does this page have a title?" against un-stripped HTML
  # sees the one we ourselves injected last run, skips re-emitting it, and then
  # loses it with the old block -- a second run would fail where the first
  # succeeded. Everything below therefore reasons about the pristine page.
  base = html
  if _BEGIN_MARKER in base:
    if _END_MARKER not in base:
      raise BrandError(
        "found the BEGIN marker without a matching END marker -- the file was "
        "hand-edited inside a previously-injected block; refusing to guess."
      )
    b_start = base.index(_BEGIN_MARKER)
    b_end = base.index(_END_MARKER) + len(_END_MARKER)
    # Also swallow the newline the insert added, so repeated runs are byte-stable.
    if base[b_end:b_end + 1] == "\n":
      b_end += 1
    base = base[:b_start] + base[b_end:]

  insert_at = _find_app_anchor(base) if anchored else _find_head_close(base)
  has_title = _TITLE_PATTERN.search(base) is not None

  if not has_title and anchored:
    raise BrandError(
      "app entry has no <title> element -- refusing to invent one, because its "
      "absence means the generated HTML changed shape."
    )

  block = render_block(prefix, title=None if has_title else title)
  out = base[:insert_at] + block + "\n" + base[insert_at:]
  return _replace_title(out, title) if has_title else out


def discover_targets(dist_root: Path) -> list[tuple[Path, str, bool]]:
  """Every brandable page as ``(path, asset_prefix, anchored)``.

  App entries live one directory below ``dist/`` so they reach the staged
  assets with ``../``; the root shell sits at ``dist/`` itself and uses ``./``.
  Sorted for determinism.
  """
  if not dist_root.is_dir():
    return []

  targets: list[tuple[Path, str, bool]] = []
  for candidate in sorted(dist_root.glob("*/index.html")):
    try:
      if _ANCHOR_PATTERN.search(candidate.read_text(encoding="utf-8")):
        targets.append((candidate.resolve(), "../", True))
    except OSError:
      continue

  root_index = dist_root / "index.html"
  if root_index.is_file():
    targets.append((root_index.resolve(), "./", False))

  return targets


def check(target: Path, prefix: str, title: str) -> None:
  """Verify *target* was branded, without modifying it."""
  html = target.read_text(encoding="utf-8")

  if _BEGIN_MARKER not in html or _END_MARKER not in html:
    raise BrandError(f"{target}: no PRAXIS-BRAND-INJECT block -- inject_branding.py never ran.")

  start = html.index(_BEGIN_MARKER)
  end = html.index(_END_MARKER) + len(_END_MARKER)
  block = html[start:end]

  found_title = _TITLE_PATTERN.search(html)
  if not found_title:
    raise BrandError(f"{target}: no <title> element at all.")
  if found_title.group(1).strip() != title:
    raise BrandError(
      f"{target}: <title> is {found_title.group(1).strip()!r}, expected {title!r} "
      "-- the page still advertises itself as upstream JupyterLite."
    )

  hrefs = _HREF_PATTERN.findall(block)
  if len(hrefs) != 2:
    raise BrandError(f"{target}: expected 2 href(s) in the block, found {len(hrefs)}: {hrefs}")

  # A <link> pointing at a path that does not exist renders as an unstyled,
  # unbranded page with no console error a build would notice.
  for href in hrefs:
    resolved = (target.parent / href).resolve()
    if not resolved.is_file():
      raise BrandError(f"{target}: block references {href!r} ({resolved}), missing on disk.")

  expected_prefix = prefix
  for href in hrefs:
    if not href.startswith(expected_prefix):
      raise BrandError(
        f"{target}: href {href!r} does not use the expected prefix {expected_prefix!r} "
        "-- the asset path is wrong for this page's depth."
      )


def main(argv: list[str] | None = None) -> int:
  parser = argparse.ArgumentParser(
    description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
  )
  parser.add_argument(
    "--dist", type=Path, default=None, help="dist root (default: <web-repl>/dist)."
  )
  parser.add_argument("--title", default=DEFAULT_TITLE, help=f"document title (default: {DEFAULT_TITLE!r}).")
  parser.add_argument(
    "--check", action="store_true", help="Verify an already-built dist without modifying it."
  )
  parser.add_argument("-v", "--verbose", action="store_true")
  args = parser.parse_args(argv)

  logging.basicConfig(
    level=logging.DEBUG if args.verbose else logging.INFO,
    format="%(levelname)s %(name)s: %(message)s",
  )

  dist_root = args.dist if args.dist is not None else DEFAULT_WEB_REPL_ROOT / DEFAULT_DIST_REL
  targets = discover_targets(dist_root)

  if not targets:
    logger.error(
      "no brandable index.html found under %s -- run build_repl.py before inject_branding.py.",
      dist_root,
    )
    return 1

  failed = 0
  for path, prefix, anchored in targets:
    try:
      if args.check:
        check(path, prefix, args.title)
        logger.debug("OK %s", path)
      else:
        html = path.read_text(encoding="utf-8")
        path.write_text(inject(html, prefix, args.title, anchored=anchored), encoding="utf-8")
        logger.debug("branded %s (prefix=%s)", path, prefix)
    except BrandError as exc:
      logger.error("%s", exc)
      failed += 1

  if failed:
    logger.error("%d/%d target(s) failed.", failed, len(targets))
    return 1

  logger.info("%s %d target(s)", "verified" if args.check else "branded", len(targets))
  return 0


if __name__ == "__main__":
  sys.exit(main())
